alcohol-study/2024-programmers

- sung-silver/hash/week1-1.java
- 폰켓몬: https://school.programmers.co.kr/learn/courses/30/lessons/1845
- 가장 큰 힌트는 아무래도 유형별 풀이이다 보니 Hash..!
- 해시 + answer를 구하는 시점 구분 잘하기
- 해시 맵에 종류 별로 폰켓몬(?)을 마리 별로 저장한다
- 선택할 수 있는 마리의 수는 N/2 이므로 선택한 마리를 식별할 counter 변수를 만들어 활용한다
- 선택할 수 있는 마리를 결정짓는 종료 조건은 다음과 같다
- counter가 0이 되어 선택할 수 있는 폰켓몬의 종류가 남아있지만 answer에 반영하지 못함
- hash 맵에 저장된 모든 종류의 포켓몬을 1마리 씩 선택을 한 경우
- 시간복잡도 : O(N)
- 해시 맵에 입력 배열을 읽어 포켓몬을 종류별로 몇 마리인지 저장하는데 O(N), 저장된 해시 맵을 한번 훑으며 counter(=numbers.length/2)를 감소시키는 로직 O(N/2)
- 공간복잡도 : O(N)
- X
> [1주차] JAVA: 폰켓몬

- sung-silver/hash/week1-1.java
- sung-silver/hash/week1-2.java
- 완주하지 못한 선수: https://school.programmers.co.kr/learn/courses/30/lessons/42576
- key와 value에 각각 어떤 값을 저장할 것인가를 위주로 생각
- key: 참가자 이름
- value: 참여자의 숫자(동명이인을 고려하기 위하여) 
- 해시맵
- 해시맵에 참가한 사람을 모두 저장한다 이때, 동명이인은 2명으로 저장한다
- 완주 목록과 비교하여 완주한 경우에 value를 감소하여 0으로 만든다
- 해시맵을 검사했을 때 value가 1 이상이라면 완주하지 못한 것이다 
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 폴더링이 안남아서 제 local에 week1-1을 머지해가지구 파일이 중복해서 올라갔는데 week1-2.java만 보시면 됩니다!!
> [1주차] JAVA: 완주하지 못한 선수

- programmers/unanchoi/hash/의상.py
프로그래머스 의상
경우의 수 문제라고 생각함.
- 경우의 수 문제로 치환해서 풀었다. 나올 수 있는 경우의 수에서 아무것도 선택하지 않는 경우 한 가지를 빼면 정답이 된다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
처음에 이중 for문으로 생각했는데, 1번 Test를 통과하지 못함 ... 수학적으로 생각하면 쉽게 구할 수 있는 문제 였음.
> [PYTHON] 의상

- hash/베스트앨범.java
베스트 장르 순서대로, 리스닝 수가 높은 상위 2개의 음악 번호를 출력하는 문제
<br>
음악 장르, 번호에 따른 총 리스닝 합을 구하거나, 서로 매칭이 되야하는 케이스라 Hash를 사용
<br>
해시맵
<br>
1. 해시맵 sumMap : <장르 : 누적리스닝합> 
2. 해시맵 countGenres : <장르 : 해당장르의 곡수 누적합> 
3. 리스트 keys : sumMap의 value 값 순서대로 가장 많은 리스닝을 한 장르를 내림차순 정렬!
4. 해시맵 genreMap : < 한가지 장르의 음악 번호 : 해당 음악의 리스닝 수>
>  해당 genreMap에서는 keys의 순서대로 해당 장르를 주어진 genre 배열에서 찾아서 같을 경우 genreMap에 넣는 식으로 진행
> 그렇다면 예를들어 한번의 반복문에서 pop 장르의 곡번호와 해당 곡의 리스닝 수가 저장된다.
> 그 후에 value 값으로 내림차순 정렬을 해서 가장 많이 들은 곡 2곡만 저장한다.
<br>
- 시간복잡도 : O(n^2) -->  반복문 두번 
- 공간복잡도 : O(n) --> 좀 많지만 중첩된 map은 없어서 O(n)
<br>
문제를 너무 꼬아서 푼것 같다. 너무 많은 변수?들을 사용한것이 아쉬웠다. 문제를 풀고나서 다른 풀이를 보니 Hash안에 또 Hash를 넣어서 잘 활용하셨던데 기억해두고 다음에 그렇게 풀어야징!
<br>
> [1주차] JAVA : 베스트앨범

- hash/의상.java
- 조합문제! 
<br>
- 조합을 다 까먹었다.... 확통....문제 느낌..? 해쉬 에 어떻게 저장하는가를 잘 생각해야했던 문제..! 
- 그냥 보면 해시 사용하는지 잘 모를 것 같다.
<br>
- 해시
<br>
1.  해시에 옷의 카테고리를 key로, value에는 카테고리별 옷의 개수를 넣는다.
2. 그 다음에는 Iterator를 사용해서 조합의 수를 구한다 ( 0-안입는경우, 1-첫번째옷을 입는 경우, 2-두번째 옷을 입는경우 ....)
3. 그리고 모든 카테고리별로 옷을 다 안입은 경우를 -1 해준다!
<br>
- 시간복잡도 : O(n) -> map에 데이터를 넣을때 사용한 반복문이 제일 많이 돌아가는 듯! 
<br>
- 조합식이 기억이 안낫나서 조금 오래 걸린것..! 아놔.. 확통 못했는데...
<br>
> [1주차] JAVA : 의상

- hash/전화번호_목록.java
- 한 번호가 다른 번호의 접두어인 경우가 있는지 확인하는 문제
<br>
- 처음에는 Hash를 사용할 필요가 없다고 생각해서 배열로 풀려고 했으나... 시간초과로 fail...
<details>
<summary>틀린 풀이(배열 사용)</summary>
<div markdown="1">
```java
import java.util.*;
class Solution {
public boolean solution(String[] phone_book) {
boolean answer = true;
Arrays.sort(phone_book, new Comparator<String>(){
@Override
public int compare(String s1, String s2){
return s2.length() - s1.length();
}
});
for(int i = 0; i < phone_book.length; i++){
for(int j = i+1; j < phone_book.length; j++){
if(phone_book[i].contains(phone_book[j])){
answer = false;
}
}
}
return answer;
}
}
```
</div>
</details>
<br>
- Hash, Array
<br>
- 배열의 값을 subString을 사용해서 map의 Key에 있는지 확인..! 어찌보면 String의 contains처럼 사용하는듯!
<br>
- 시간복잡도 : O(n)..?   : phone_book의 요소 크기 만큼 내부 반복문은 20번만 진행하니까.. 입력 …
> [1주차] JAVA : 전화번호 목록

- hellozo0/hash/완주하지_못한_선수.java
- hellozo0/hash/폰케몬.java
- 참가자 n 명에 대해, 완수자는 n-1인 제한 조건일때, 완수하지 못한 1명을 구하는 문제
- 동명이인 존재 ㅇ
<br>
- HashMap의 유형문제라는 것을 미리 알지 못했으면 어떻게 해야하는지 처음에 애 먹었을 것 같았다.
- 그래도 Hash의 유형이라는 것을 알았기에... 다행스... 이렇게 유형 하나씩 잡아가는거 good..
<br>
- Hash
<br>
1. 참가자 수만큼 Hash에 넣고, 만약 동명이인이면 value++한다.
2. 완수자가 Hash에 있다면 remove 또는 value--를 한다. 
3. map에 하나 남은 요소 저장하고 return
<br>
- 시간복잡도 : O(n) -> 반복문 1개 
- 공간복잡도 : O(n) -> HashMap 이 참가자 수만큼 요소가 만들어진다.
<br>
- 문제의 return 이 1개로 fix인지 몰라서 엥? 왜 자꾸 return 에러가 나지.? 했다.. 문제를 좀더 꼼꼼히 읽을 것..! 
- HashMap의 다양한 메소드를 익히는 것이 목표..!
<br>
> [1주차] JAVA: 완주하지 못한 선수 

- hellozo0/hash/폰케몬.java
[문제링크](https://school.programmers.co.kr/learn/courses/30/lessons/1845)
폰케몬 의 절반 만큼 가져갈 수 있는데 최대한 많은 종류의 수를 가져가는 방법에 대한 문제!
Hash관련 문제라 Hash에 대한 개념 공부를 하고 시작을 했다. 
[공부링크1](https://coding-factory.tistory.com/556)
[공부링크2](https://kadosholy.tistory.com/120)
Hash는 중복된 Key 값이 있으면 덮어쓰기를 한다. 따라서 중복 키가 있으면 value +1 을 했다. --> 사실 이 부분 무의미했다. 
- Hashmap 문제 
<br>
1. 먼저 map에 num배열의 값을 키로 해서 값을 다 넣는다.
- 여기에서 이미 있는 값이면 value++ 를 했는데 사실 의미 없는 코드다. 
2-1. 만약 N/2보다 map의 size 더 크면 종류가 많은것이니 N/2를 return
2-2. map의 size가 더 적으면, 중복값이 많은것이니 Map의 size만큼을 return
<br>
- 시간복잡도 : O(n) --> Hash에 값을 넣는 반복문 하나 
- 공간복잡도 : O(n) --> Hash에 들어가는 공간
<br>
HashMap 으로만 풀려고 했다는 것..! 다른 사람들의 풀이를 보니 Set으로 문제를 많이 풀었는데 빠른 판단 후 적절한 자료구조를 골라야하는 눈이 아직 부족하다.
> [1주차] JAVA : 폰켓몬

- programmers/unanchoi/hash/전화번호목록.py
전화번호 목록
해시
해시를 활용해서 풀려고 했는데, 감이 잘 안옴
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
`startswith()` method를 사용하면 구현이 훨씬 쉽고 단순해지는데, 쉽게 떠올리지 못했따.
> [PYTHON] 전화번호 목록

- .github/programmers/unanchoi/hash/폰켓몬.py
https://school.programmers.co.kr/learn/courses/30/lessons/1845
자료구조에 집중하기 보다는 해결점을 파악해보려고 함.
해시
python의 Counter를 쓰니까 쉽게 풀림.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
문제를 정확하게 이해하지 못해서 푸는데 오래걸림.
> [PYTHON] 폰켓몬

- programmers/unanchoi/hash/완주하지못한선수.py
https://school.programmers.co.kr/learn/courses/30/lessons/42576
- 동명이인을 어떻게 고려할까?
- 해시
- 반복문을 돌면서 값 확인.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 처음 풀이가 이중포문이어서 효율 성 검사에서 통과하지 못함
> [1주차] PYTHON : 완주하지못한선수

- programmers/unanchoi/hash/베스트앨범.py
베스트 앨범
해시
장르,횟수, 인덱스 3개를 한방에 저장해서 풀이함~
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- defaultdict()를 생각하지 못함. 그래서 생으로 구현하려고 했는데, 쉽지 않았다.
> [PYTHON] 베스트 앨범

- sung-silver/hash/week1-1.java
- sung-silver/hash/week1-2.java
- sung-silver/hash/week1-3.java
- 전화번호 목록: https://school.programmers.co.kr/learn/courses/30/lessons/42577
- 입력되는 전화번호를 Key로 사용해야겠다고 생각함!
- 해시
- 입력되는 전화번호를 Key로하여 해시 맵에 저장한다
- 다시 입력된 전화번호 배열을 String으로 하나하나 가져와서(이 가져온 문자열을 s라고 하자) s가 key로 사용되는 문자열들에 포함되는지를 검사한다 -> 접두어가 포함되는지 검사하는 로직
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 큭큭 이거 브랜치가 머지가 안된 상태라 이전 커밋이 계속 쌓이네요 ^_^ 브랜치 관리 어케해야할지도 한번 얘기해야할듯 합니더~
> [1주차] JAVA: 전화번호 목록

- sung-silver/hash/week1-4.java
- 의상을 입는 조합을 구하는 문제
- 문제 조건의 상황: 각 옷의 유형 중 0개 이상을 선택할 수 있다. 전체 옷 중 1가지는 무조건 선택해야 한다
- 조합, HashMap 사용
- 각 종류별 의상의 개수 + 1 를 한 숫자들을 곱한다
- 각 종류별 의상을 하나도 고르지 않는 조합 1개를 제외한다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 오래전에 풀었던 문제인데! 호닥 지우고 푸는데 다행이 방향을 잘 잡았던 것 같다 킥
> [1주차] JAVA: 의상

- .idea/workspace.xml
- Hong0329/hash/week1-5.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42579
* 값 정렬을 잘해보자.
* 자료구조
* 장르에 따른 재생 횟수를 더한 맵을 만들어준다.
* 장르 번호 재생횟수 를 모두 표함하는 맵을 만들어준다.
* 위를 잘 정렬하여 값을 도출한다.
- 공간복잡도 : O(n)
* 풀면서 맵이랑 너무 안친한게 느껴져서(쓰는데 뭔가 어색함ㅜ) 좀 더 문제를 많이 풀어봐야겠다...예전에 뭐든 벡터랑 배열로만 풀려고 했던 습관이 이런 결과를 만들어낸 것 같다.
> [1주차] C++: 베스트 앨범

- sung-silver/hash/week1-5.java
- 베스트앨범: https://school.programmers.co.kr/learn/courses/30/lessons/42579
- 우선순위를 고려
- 해시
- 먼저 장르별 재생 횟수를 모두 더한 해시맵을 만든다
- 장르별 <고유번호, 재생횟수> Map을 가지는 해시맵을 만든다
- 최대 재생 횟수를 가지는 장르부터 차례대로 노래를 선택한다(최대 2개)
- 공간복잡도 : O(N)
- 일단 해시의 값 기준 정렬을 잘 모르겠어서 구글링을 많이 해보았던 것 같다
- 다 풀고나니 반복문의 중첩이 너무 많아서 아쉽다 특히 while 안의 로직이 복잡해진 것 같다 뭔가 구현에 너무 치중한 느낌..
- 아래 코드에서 compare 대신 원래 사용하던 genre 변수를 사용하면 에러가 발생했다
- 에러 메시지: local variables referenced from a lambda expression must be final or effectively final
`Collections.sort(keySetList, (o1, o2) -> (playCount.get(compare).get(o2).compareTo(playCount.get(compare).get(o1))));`
- 람다식에 대해 좀 더 공부해보아야 할 것 같다 특히 이번 문제에서 해시맵을 정렬하기 위해 위와 같은 compareTo 식을 작성하면서 더더욱 느꼈다
> [1주차] JAVA: 베스트앨범

- programmers/sung-silver/stack-queue/week2-1.java
- 같은 숫자는 싫어: https://school.programmers.co.kr/learn/courses/30/lessons/12906
- 연속된 숫자의 중복을 없앤다가 point!
- 스택의 상단 값과 현재 push할지 말지에 대한 값을 비교해서 같으면 push하지 않고 다르면 push
- 스택을 사용한다
- 처음에 삽입하는 값은 비교할 값이 없으므로 무조건 Push 한다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 처음에 단순 중복을 모두 없애는줄 알고 Set을 생각함.. 문제를 잘 읽자
> [2주차] JAVA: 같은 숫자는 싫어

- programmers/sung-silver/stack-queue/week2-3.java
- 올바른 괄호: https://school.programmers.co.kr/learn/courses/30/lessons/12909
- 닫는 괄호보다 여는 괄호에 집중했다!
- 스택
- ')'가 등장하기 전 마지막 '(' 부터 ')'와 매치하는 방식
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 처음에 열린 괄호면 count를 증가하고, 닫힌 괄호이면 count를 감소시키는 방식을 생각했는데, 이럴 경우에는 스택을 쓰는 의마가 없을 뿐더러 `())((()))(()` 이런 테스트케이스에서 실패하는 것을 발견했다
- 짝을 매치해야하는 문제에서는 스택을 사용하는게 좋다는 것을 느꼈음!
> [2주차] JAVA: 올바른 괄호

- programmers/sung-silver/stack-queue/week2-5.java
- 다리를 지나는 트럭: https://school.programmers.co.kr/learn/courses/30/lessons/42583
- 무게에 따라 올라갈 수 있는 트럭이 제한되는 상황을 보고 큐를 사용해야겠다고 생각했다
- 큐
- 처음에는 Pair 클래스를 만들어 남은 다리의 길이와 해당 트럭의 무게를 담고 이를 모두 큐에 넣으려고했었다..
- 그러나 계속해서 1초 단위로 비교해야하는 것이 비효율적이라고 생각되었고, 예전에 푼 풀이를 보고 앗차 싶었다(트럭이 지나가는 다리를 큐로 둘 생각을 그때도 못했던 것 같음)
- 다리를 큐로 두고 만약 다리가 버틸 수 있는 무게를 넘기면 0을 큐에 집어 넣어 시간을 흘려보낼 수 있다!
- 더하여 다리가 버틸 수 있는 무게에 비해 트럭의 무게가 전반적으로 가벼우면 다리위에 트럭이 가득차는 경우도 고려해주어야 했다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- X!!! 근데 갑자기 궁금한게 다들 큐에서 while 두번쓰면 시간복잡도 어케 계산함? 나는 O(N)이라고 생각했는데 아닌 사람들도 좀 있는거같애서 큭큭
> [2주차] JAVA: 다리를 지나는 트럭

- programmers/unanchoi/stack/같은숫자는싫어.java
- programmers/unanchoi/stack/기능개발.py
https://school.programmers.co.kr/learn/courses/30/lessons/42586
-  문제 자체가 길지만, 문제를 이해하고 1차 가공했을 때를 기준으로 문제를 해결
- 스택, 큐
- 결국 쌓여있는 값의 최댓값보다 가장 큰 값이 나오기 전까지 숫자를 더해주면 되는 문제다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 알고 보면 매우 쉬운 문제였는데, 문제 풀이 방법을 찾는데 오래 걸렸다.
> [2주차] PYTHON: 기능개발

- programmers/unanchoi/stack/같은숫자는싫어.java
- programmers/unanchoi/stack/주식가격.py
https://school.programmers.co.kr/learn/courses/30/lessons/42584
- 루프를 돌면서, 자기 자신 인덱스 이후로 자신 보다 작은 수가 있는지 찾는다.
- 스택, 큐
- 루프를 돌면서, 자기 자신 인덱스 이후로 자신 보다 작은 수가 있는지 찾는다.
- 공간복잡도 : O(N)
- 처음에 문제이해를 못함 ㅋㅋ
> 2주차 : [PYTHON] 주식가격

- programmers/unanchoi/stack/같은숫자는싫어.java
- programmers/unanchoi/stack/다리를지나는트럭.py
https://school.programmers.co.kr/learn/courses/30/lessons/42583
-  스택, 큐를 적극적으로 활용하는 문제는 아니었던 것 같음.
- Stack, Queue
- 대기 트럭에서 다리 위로 매 초마다 보내주고, 다리 위의 트럭을 매초마다 건넌 트럭으로 옮겨준다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- sum 함수를 쓰니 시간초과가 떴다..
- 처음에 문제를 잘못 이해했음. 트럭이 1초에 1씩 이동할 수 있다는걸 늦게 알아버림. 다리를 건너는 트럭을 빈 배열로 만들었는데, 그러다보니 구현이 어려웠음.
> 2주차 : [PYTHON] 다리 위를 지나는 트럭

- programmers/Hong0329/stack-queue/week2-1.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12906
* 이전에 입력 받은 것과 현재 입력 받은 값이 같은지 체크한다.
* 같으면 통과, 다르면 answer에 추가
* 입출력
* 이전에 입력 받은 것과 현재 입력 받은 값이 같은지 체크한다.
* 같으면 통과, 다르면 answer에 추가
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
* 처음에 문제를 보고 전체에서 중복된 값들을 제외하고 입력받은 순서대로 출력하는 것으로 잘못 이해했었다.
* 문제와 예제를 꼼꼼하게 읽어보자...
> [2주차] C++: 같은 숫자는 싫어

- programmers/Hong0329/stack-queue/week2-2.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42586
* 큐에 작업들을 순서대로 넣어놓은 후에, 하루마다 일을 하면서 처리해주기
* 큐
* 현재 가장 먼저 배포되어야할 작업을 지정해놓고(큐를 통해서) 해당 작업이 완료되었을 때 버로 다움 작업이 완료되었는지 확인하여, 최대한 많이 연속된 작업양을 cnt+=1을 통해서 구해준다. 
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
처음에 우선순위큐를 사용하여 하루하루가 지날 때 마다 완료된 것은 우선순위큐에 넣고, 해당 큐의 top()의 값이 현재 가장 먼저 진행되어야할 작업이라면 cnt++을 해주는 방식으로 진행하였는데 이러면 작업이 완료되어 우선 순위 큐에 넣을 때 마다 내부에서 sort가 돌기 때문에 시간이 초과되었다. 굳이 이렇게 할 필요가 없었다....
> [2주차] C++: 기능개발

- programmers/Hong0329/stack-queue/week2-3.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12909
* (가 나오면 변수를 증가, )나오면 감소시키면서 음수가 되거나 다 돌았을 때 0이 아니면 false아니면 true
* 입출력/스택
* (가 나오면 변수를 증가, )나오면 감소시킨다.
* 중간에 변수가 음수가 되거나 다 돌았을 때 0이 아니면 false를 반환한다.
* 이외의 경우는 true
- 시간복잡도 :O(n)
- 공간복잡도 :O(n)
* 스택큐 문제셋인걸 알면서도 그냥 빠르게 생각나는 방식으로 접근한 것,,,
* 오히려 분기처리가 더 귀찮았던 것 같다.
> [2주차] C++: 올바른 괄호

- programmers/Hong0329/stack-queue/week2-4.cpp
*https://school.programmers.co.kr/learn/courses/30/lessons/42587
* 자료구조와 정렬
* 자료구조와 정렬을 사용하여 풀어보자.
1. 중요도에 대해서 중요도와 인덱스를 pair형으로 만들어서 vector와 queue에 각각 넣어준다.
2. vector에서 sort를 통해 <a,b>값에 대해서 a는 내림차순,.b는 오름차순으로 정렬한다. -> 프로세스의 처리 순서
3. vector와 queue를 while문을 통해 비교해주면서 현재 보는 vector와 queue.front()가 같으면 프로세스 횟수(cnt)를 증가시키며 진행한다.
4. 이때 que.front().second == location라면 그때의 cnt값이 answer가 된다.
- 시간복잡도 :O(n^2) => while문 안에 while문
- 공간복잡도 :O(n)
* 굳이 할 필요 없는 변수 선언....
* 어차피 작업리스트가 순서가 있게 제공되고, 그 순서에 따라서 중요도가 다르면 que.push(que.front()), que.pop()하기 때문에 지금 생각해보니 index까지 pair형으로 저장을 안했어도 됐을 것 같다....
> [2주차] C++:프로세스

- programmers/Hong0329/stack-queue/week2-5.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42583
* pair를 통해 트럭의 무게와 현재 위치를 같이 저장하고 이를 통해 답을 구해보자.
* 자료구조
1. 앞에 있는 트럭부터 페어형 벡터에 집어넣는다. 이때 페어는 (현재 위치, 트럭의 무게)로 집어넣는다.
2. 위의 과정에서 트럭이 벡터에 들어갈 경우 도로에 올라간 것으로 간주하여 트럭의 무게를 전체 도로 위의 트럭 무게의 합(sum)에 더해준다.
3. if문을 통해서 벡터의 가장 앞에 있는 트럭의 위치가 도로의 길이와 같아지면 도로를 다 건넜다는 뜻이므로, sum에서 해당 트럭의 무게를 빼주고, 벡터에서도 제외해준다.
4. 또다른 if문을 통해서 만약 아직 대기중인 트럭이 있고, 도로 위에 올라갈 수 있는 무게라면 해당 트럭을 (0,트럭무게)로 벡터에 집어넣고,sum을 무게만큼 증가시킨다.
5. 3번과 4번 과정을 벡터가 빌 때 까지 while문을 통해 돌려주며, while문이 한 번 돌때 시간과, 벡터에 있는 트럭들의 위치를 1씩 증가시켜준다.
- 시간복잡도 :O(n^2) =>while문 안에 for문
- 공간복잡도 :O(n)
* stack-queue문제집인데 해당 자료구조를 사용해서는 못풀겠는 점...더 공부할게요...
> [2주차] C++: 다리를 지나는 트럭

- programmers/hellozo0/heap/이중우선순위큐.java
최대힙 최소힙을 사용하는 문제
<br>
문제 이름에서부터 우선순위큐...어쩌구..
<br>
우선순위 큐
<br>
1. 최대힙, 최소힙 두가지를 사용한다.
2. 연산자가 I일 경우 두 힙에 값을 넣고
3. 연산자가 D 일 경우 1이냐 -1이냐에 따라 값을 빼준다. 
4. 그리고 꼭 잊지 않고 max에서 뺐으면 min큐.remove(뺀 숫자 적기) 반대 힙에서도 해당 숫자를 빼줘야한다
<br>
- 시간복잡도 :  O(n) -> 입력개수 만큼 반복문을 수행한다
- 공간복잡도 : O(n) -> I가 n개 일 경우
<br>
처음에 'I', 'D' 이런식으로 비교를 햇는데 자꾸 틀리는 거다...
그래서 로그를 찍어보니까 if문을 수행하지 않고 있었던것임!! ''는 char 비교인데... ""를 썼어야했는데.. 어처구니 없는 실수..~
<br>
> [3주차] JAVA : 이중우선순위큐

- programmers/unanchoi/heap/디스크컨트롤러.py
https://school.programmers.co.kr/learn/courses/30/lessons/42627
Heap
- 현재 처리 할 수 있는 job들만 최소heap에 넣어서, 정답에 더해준다.
- 공간복잡도 : O(N)
- 아이디어는 떠올렸는데, 구현이 어려워서 힌트를 봤습니다 ..
-  구현 문제라고 생각하고, 꼭 Heap을 사용하지 않아도 풀 수 있는 풀이들도 있더라고요.
https://school.programmers.co.kr/learn/courses/30/lessons/42627
> [3주차] PYTHON:  디스코컨트롤러

- programmers/hellozo0/heap/더_맵게.java
heap을 사용해서 첫번째 두번째 로 큰 값을 연산해서 K보다 커지려면 몇번의 연산을 수행해야하는가~ 하는 문제
<br>
heap이라는 유형이 있어서 heap을 구현하려고 했다!
<br>
heap -> 나중에는 우선순위 큐를 사용한다는 것을 깨달았음!
<br>
1. 우선순위큐는 최소힙을 따르도록 기본설정되어 있다.
2. 우선순위 큐에 스코빌 지수 값을 넣으면서 알아서 sorting 된다.
3. 맨 앞에 있는 값이 계산 된 값이니 그 값이 K 보다 작다면 반복문을 계속 수행한다.
- 큐에 값이 2개 보다 적다면 K를 절대 넘을 수 없다는 뜻이므로 -1를 리턴
- 값을 계산하고 또 큐에 넣는다. ( 그리고 맨 앞에 2값은 뺀다) 
<br>
- 시간복잡도 : O(n) --> 스코빌 지수 만큼 큐에 값을 넣어서?! 근데 입력 하는 것도 시간 복잡도에 포함이겠죠?
- 공간복잡도 : O(n) --> 처음에 스코빌 값의 모든 값을 큐에 넣는다. 그래서 입력 값 만큼 공간이 생김
<br>
처음에 힙 개념을 공부하고 문제를 풀었는데 아니 너무 코드가 긴데... 도 불구하고 일단 구현을 했다만
한가지 테스트케이스 빼고는 다 틀렸다... ㅎㅎ~ 그래서 더 찾아보니 힙이 우선순위큐로 그냥 간단히 구현이 되었다는 점... 
그래서 풀다 보니 while문 안에 "만약 데이터가 2보다 작아졌는데 반복문을 타고 있으면 1개밖에 없는거므로 모든 음식의 스코빌 지수를 K이상으로 만들 수 없는것이다 -- -1을 리턴한다." 이 부분을 미처 계속 생각하지 못했다..~ 여튼 예외케이스 ? 중단되는 케이스를 잘 생각해야할듯
<br>
<br>
> [3주차] JAVA : 더 맵게

- programmers/Hong0329/heap/week3-1.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42626
* 문제에 주어진 방식으로 음식들을 맵게 했을 때 K가 넘으려면 몇 번 거쳐야 하는지 구하는 문제
* 자료구조(우선순위 큐)
* 우선순위 큐를 이용하여 가장 안매운 음식을 시작으로 정렬한다.
* 문제에 주어진 방식으로 음식을 섞고 다시 목록에 넣는다.
* 현재 있는 음식들 중에 우선순위큐 가장 앞에 있는 것이 안매운 음식이고, 그 음식이 K보다 맵다면 break
- 시간복잡도 :O(nlogn) -> 우선순위 큐의 삽입은 logn의 시간복잡도, while문이 가장 안좋은 조건을 돌면 n-1번 돌아가게됨.
- 공간복잡도 :O(n)
* while문 안에서 pop을 두 번 하게 되는데 처음에 while문 조건을 empty()로 두었다가 계속 core dump가 떴다(두 번째 값이 큐에 없을 수도 있기 때문에) 좀 더 신경써서 문제 풀기
> [3주차] C++: 더 맵게

- programmers/Hong0329/heap/week3-2.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42627
* 어떻게 해야 짧을지에 대한 점화식을 설정하고 그것에 맞춰서 진행
* 자료구조(우선순위큐)
* 현재 작업할 수 있는 업무들 중에(현재 시간이 업무가 들어온 시간보다 이후일때) 작업에 걸리는 시간이 가장 적은 업무를 먼저 진행하는 것이 최적의 해를 구할 수 있는 방법이다.
* 들어온 순서대로 업무를 정렬한 후에 정렬된 업무를 현재 시간과 비교하며 작업이 가능한 업무들에 대한 우선순위큐를 만들어 저장한다.
* 이때 우선순위 큐는 작업에 걸리는 시간이 적은 것이 앞으로 오게 한다.
- 시간복잡도 :O(nlogn)
- 공간복잡도 :O(n)
* 무작정 배열과 pair로 처리하려고 했던 점,,,
> [3주차] C++: 디스크 컨트롤러

- programmers/sung-silver/heap/week3-2.java
- 디스크 컨트롤러: https://school.programmers.co.kr/learn/courses/30/lessons/42627
- 운영체제의 스케줄링과 비슷하다고 생각했다.. 근데 무슨 기법이었지
- 우선순위 큐
- case를 2개로 나눈다
- 일단 진행 중인 작업이 있을 때 들어오는 작업은 큐에 넣는다
- 큐가 비어 있다면 작업이 완료되고 다시 작업이 들어온다
- 작업이 끝나기 전  가장 수행시간이 짧은 요청부터 수행한다
- 시간복잡도 : O(NlogN)
- 입력 값의 순서가 job이 들어오는 순서를 보장하지 않는다는 것을 .. 조금만 더 빨리 알았더라면
- 자료의 형태?라고 해야할까 개인적으로 jobsIdx를 활용하는 방법이 너무 어려웠다
> [3주차] JAVA: 디스크 컨트롤러

- programmers/Hong0329/heap/week3-3.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42628
* 정렬 방식이 반대인 우선순위큐 2개 사용
* 우선순위 큐
* 오름차순, 내림차순 2개의 우선순위 큐를 선언하고 값을 넣는다.
* 값을 밸 떄 현재 두 개의 큐에 들어간 숫자의 개수와 빠진 숫자의 개수를 비교하여 0일 경우 두 개의 큐를 모두 비워준다.
- 시간복잡도 :O(nlogn)
- 공간복잡도 :O(n)
> [3주차] C++: 이중우선순위큐

- programmers/sung-silver/sort/week4-1.java
- K번째 수: https://school.programmers.co.kr/learn/courses/30/lessons/42748
- 배열을 slice하고 정렬한 후 들어온 값의 위치에 있는 값을 정답 리스트에 추가
- 정렬
- 단순하게 입력받은 commands를 돌면서 계산을 진행
- 공간복잡도 : O(n)
- start 인덱스는 -1을 해야하는데 end 인덱스는 그렇지 않고 그 위치 그대로 사용해야 한다는 것을 처음에 놓쳤었다(당연한게 같거나 작다로 했으니..^_^_)
- 정렬을 단순 라이브러리를 써서 구현했는데 이게 맞나 싶다.. 보통 이런 문제는 정렬자체를 시키려나?
> [4주차] JAVA: K번째 수

- programmers/sung-silver/sort/week4-2.java
- 가장 큰 수: https://school.programmers.co.kr/learn/courses/30/lessons/42746
- 앞 뒤로 붙인 문자열 자체를 비교
- 정렬
- 문자열 A+B를 int로 변환한 값이 큰지 B+A를 한 값이 큰지를 기준으로 숫자들을 정렬
- 공간복잡도 : O(n)
- 개인적으로 comparator를 자유자재로 쓰지 못해 아쉬웠다(그래서 많이 헤맸음..)
- 앞 뒤로 붙인 것이 더 큰가?에 대한 힌트를 여기서 얻었다 https://school.programmers.co.kr/questions/51327
- 힌트와 무수한 구글링이 없었다면 못풀었을 것 같음..ㅎ
> [4주차] JAVA: 가장 큰 수

- programmers/hellozo0/sort/K번째수.java
정렬과 배열 범위 지정해서 copy!
<br>
딱 보고 배열 범위지정해서 복사해야겠다 생각했따..!
<br>
정렬, 배열
<br>
1. 배열을 원하는 조건에 맞게 복사를 한다
2. 정렬을 한다
3. 해당 값을 answer에 넣는다
<br>
- 시간복잡도 : O(nlogn) -> command의 개수 만큼 진행된다 그리고 Arrays.sort의 시간 복잡도는 nlogn이라 한다!
- 공간복잡도 : O(n)..? -> 최악의 경우, array 전체 사용하는 경우가 있어서
<br>
음 없다..!
<br>
> [4주차] JAVA : K번째수

- programmers/unanchoi/sort/H-Index.py
https://school.programmers.co.kr/learn/courses/30/lessons/42747#
- 문제를 차근 차근 읽고, 맞춰서 구현함.
- 문제 상황을 만족하는 h 들을 list에 저장해서, max값을 출력함.
- 공간복잡도 : O(N)
- 문제가 매우 헷갈림 ... h,, h,, h,,
- 시간 절약할려고, 범위를 줄였더니 테스트 케이스에서 걸려서, 범위 늘림.
> [4주차] PYTHON: H-index

- programmers/unanchoi/sort/가장큰수.py
https://school.programmers.co.kr/learn/courses/30/lessons/42746?language=python3
- 정렬되는 조건을 찾아서, 그에 맞춰서 정렬해주고 값을 더해준다.
- SOrt
- 더했을 때, 큰 수를 비교해가면서 문제를 푼다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 구현으로 풀려고 했는데, 생각보다 잘 안풀려서 ... 정렬을 어떻게 해야지 하고 고민하다가 구글링 하면서, python functools의 cmp_to_key 라는 method를 찾았습니다... 원하는 정렬 방법대로 정렬해주는 좋은 메소드네여.
> [4주차] PYTHON : 가장큰수

- programmers/unanchoi/sort/K번쨰수.py
https://school.programmers.co.kr/learn/courses/30/lessons/42748
- 간단한 정렬 문제
- Sort
- 슬라이싱 후에 sort()로 간단하게 풀이 가능.
슬라이싱이 있어서 만약, 각 Array의 원소개수가 많았으면, 시간 초과되었을 수도 ..?
python sort() : O(nlogn)
- python으로 풀었네욤 ..^^ 다른 언어로도 시도해보면 좋을듯
> [4주차] PYTHON: K번째수

- programmers/Hong0329/sort/week4-1.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42748
* 단순 정렬
* 정렬
* 문제에서 주어진 범위를 임의의 벡터에 넣고 정렬한 후에 문제에서 원하는 순번의 값을 answer벡터에 집어 넣었다.
- 시간복잡도 :O(n^2)
- 공간복잡도 :O(n)
이중for문만이 정답일까..?
> [4주차] C++: K번째수

- programmers/Hong0329/sort/week4-2.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42746?language=cpp
* 문자열로 바꿔서 정렬하기
* string 정렬
* 입력받은 int 숫자를 string으로 바꾼 후에 a+b>b+a의 cmp를 통해서 sort한다.
- 시간복잡도 :O(nlogn)
- 공간복잡도 :O(n)
* 없습니다.
> [4주차] C++: 가장 큰 수

- programmers/Hong0329/sort/week4-3.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42747
* 문제에서 제시하는 조건에 맞는 규칙을 찾아야 한다.
* 정렬
* 주어진 논문 인용된 횟수들을 역으로 정렬한 후로 for문을 돌면서 i랑 citations[i]값을 비교한다. i -> 현재 논문보다 많이 인용된 논문의 개수를 의미하기 때문
- 시간복잡도 :O(n)
- 공간복잡도 :O(n)
* 역으로 정렬하여 문제를 풀 생각을 너무 늦게 했다....한 번은 역으로 돌려볼 생각을 초반부터 염두해뒀어야했는데...재활하자....
> [4주차] C++: H-index

- programmers/hellozo0/sort/가장_큰_수.java
주어진 숫자를 이어붙여서 가장 큰 값의 조합을 출력
<br>
값의 크기를 비교해야해서 정렬이라는 것을 떠올렸다
<br>
정렬
<br>
1. int -> String으로 새로운 배열을 만든다.
2. 문제에 나온 문자열 비교 기준에 따라 정렬한다.
3. StringBuilder를 사용해서 문자열 append 해준다 --> String 보다 더 좋은 성능 / StringBuilder는 단일스레드?에 적합
<br>
- 시간복잡도 : O(nlogn) : Arrays.sort의 시간복잡도
- 공간복잡도 : O(n) : int -> String한 배열..!
<br>
... Arrays.sort의 문자열 정렬이 되는지 몰랐다......
<br>
> [4주차] JAVA : 가장 큰 수

- programmers/hellozo0/sort/H-index.java
h번 이상 참조(?)된 책이 h개 이상 있다면 h의 최대값을 구해라잉
<br>
정렬 후 로직 생각
<br>
정렬보다는... 구현..?
<br>
1. 정렬한다.
2. 그 다음 참조 값이랑 해당 변수를 역순으로(?) 접근한다
<br>
- 시간복잡도 : nlogn -> sort 정렬!
- 공간복잡도 : n
그 아이디어 떠오르는게 넘 어려어ㅜㅆ따..... 하..
<br>
> [4주차] JAVA : H-index

- programmers/sung-silver/bf/week5-1-refactor.java
- programmers/sung-silver/bf/week5-1.java
- 최소직사각형: https://school.programmers.co.kr/learn/courses/30/lessons/86491
- 각 길이를 어떻게 처리할까를 고민하면 좋았을 것 같은데 깨닫는데 너무 오랜시간이 걸렸다 ㅎ
- 완전탐색
- 주어지는 길이 중에 더 긴 쪽을 가로, 짧은 쪽을 세로로 리스트에 저장한다
- 저장한 각 리스트를 정렬하여 최대 값을 곱한다
- refactor의 경우: O(n) 
- PR을 작성하면서 든 생각인데 결론적으로 Max만 필요하니까 리스트가 아니라 지금 width, height의 최대 값으로 갱신시켜서 O(N)의 시간복잡도를 갖게 할 수 있었을 것 같기도하네요..?
- 리팩터링하여 따로 파일 하나 더 commit 했습니다!
> [5주차] JAVA: 최소직사각형

- programmers/sung-silver/bf/week5-2.java
- 모의고사: https://school.programmers.co.kr/learn/courses/30/lessons/42840
- 각 수포자들의 규칙성을 찾는다
- 완전 탐색
- 각 수포자들의 패턴을 배열로 저장하여 나머지를 사용해 정답과 비교한다!
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 없다!
> [5주차] JAVA: 모의고사

- programmers/sung-silver/bf/week5-3.java
- 소수 찾기: https://school.programmers.co.kr/learn/courses/30/lessons/42839
- 만들 수 있는 경우의 수를 다 만들기
- 순열, 완전탐색
- 순열로 가능한 숫자를 만든다
- set에 저장하여 중복을 피한다
- 2에서부터 √N의 값까지 검색하여 소수를 판별한다
- 시간복잡도 : O(n!) -> 순열을 만드는데 드는 시간
- 공간복잡도 : O(n)
- 어떤 방식으로 풀이할건가요에 대해서는 머리로 정리를 잘 한 것 같은데, 순열을 만드는 과정에서 어떻게 접근해야할지 좋은 방법이 떠오르지 않았습니더.. 자료구조 배울 땐 어떻게 구현했담
- 그러다가 여러 글들을 보면서 DFS와 비슷한 점이 있다는 것을 알게 되었습니다!
- https://velog.io/@dev-redo/%EC%86%8C%EC%88%98-%EC%B0%BE%EA%B8%B0 이 블로그가 제일 사진을 그려두어서 그런지 이해가 잘됐음.. 여기서 이해하고 코드로 짜니까 금방 구현은 되었는데 다음에는 이런거 안보고도 스스로 구현이 가능해지길 ^_^
> [5주차] JAVA: 소수 찾기

- programmers/sung-silver/bf/week5-4.java
- 카펫: https://school.programmers.co.kr/learn/courses/30/lessons/42842
- 이전에 풀었던 문제라서 식을 어떻게 세웠었지를 고민함..
- 사각형의 넓이를 구하는 문제고, 완전 탐색으로 가로/세로 길이를 하나씩 비교
- 노란 타일의 개수는 타일의 총 (너비-2)*(높이-2)임을 고려해야한다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 식을 바로 생각해내지 못한게 아쉬웠다 생각보다 오래걸렸음..
> [5주차] JAVA: 카펫

- programmers/sung-silver/bf/week5-5.java
- 피로도: https://school.programmers.co.kr/learn/courses/30/lessons/87946
- 다 대입해보는게 답이다
- 완전 탐색
- dfs를 활용함
- 시간복잡도 : O(n!)
- dfs 아직도 잘.. 모르겠음 이전에 조합을 모두 만드는 문제처럼 접근했다가 인자가 두개라서 해시맵에 클래스를 넣어서 만들어보기도했는데 그렇게도 풀 수 있기도 하겠지만..! 어쨌든 각 순서를 서로 다른 순서로 정렬했을 때 몇번째까지 방문할 수 있는지가 point인 것 같다
> [5주차] JAVA: 피로도

- programmers/sung-silver/bf/week5-6.java
- 모음사전: https://school.programmers.co.kr/learn/courses/30/lessons/84512
- 사전이면 단어와 단어 사이에 존재할 수 있는 개수가 정해진다고 생각했다
- 완전탐색으로 유형이 분류되어 있었지만 나는.. 수학의 규칙?으로 풀이한듯
- 5자리중 맨 끝자리가 변하려면 1증가 (5^0)
- 5자리중 마지막 4번째 자리가 변하려면 6 증가 (5^1+5^0)
- 5자리중 마지막 3번째 자리가 변하려면 31 증가 (5^5+5^1+5^0)
- .. 이런 규칙을 발견하여 적용
- 시간복잡도 : O(N) 
- 공간복잡도 : O(N)
- 완전탐색으로 풀지 않아서 빨리 풀은 느낌? 근데 다른 사람들 풀이 보니까 이 문제는 다양하게 푸는 것 같다!
> [5주차] JAVA: 모음사전

- programmers/unanchoi/bf/모음사전.py
https://school.programmers.co.kr/learn/courses/30/lessons/84512
브루트포스
- permutation을 만들어서, 사전식으로 배열한 뒤에 input이 몇번쨰에 해당하는 지 return한다.
- ### 시간복잡도 공간복잡도를 어떻게 고려했나요?
- 공간복잡도 : O(N)
- 메모리 절약 방법?
> [PYTHON] 모음 사전

- programmers/unanchoi/bf/피로도.py
https://school.programmers.co.kr/learn/courses/30/lessons/87946
모든 경우의 수를 순열로 만들어서, 계산 해줌.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 처음에 순열 만들 때,  list로 안바꿨더니 계속 정답이 아니어서 .. 삽질했네여
> [PYTHON] 피로도

- programmers/unanchoi/bf/카펫.py
https://school.programmers.co.kr/learn/courses/30/lessons/42842
규칙성을 파악하려고함.
Bruteforce
전체 Tile수와 Brown, Yellow의 개수에 따른 규칙성을 파악했습니다!
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
for 문 2개 돌려서 생각했는데, 시간에서 계속 걸렸었습니다 ..
> [5주차] PYTHON: 카펫

- programmers/unanchoi/bf/모의고사.py
https://school.programmers.co.kr/learn/courses/30/lessons/42840
- Bruteforce
- 정답을 순회하면서, 값 비교
- 공간복잡도 : O(N)
조금더 짧게 풀이할 수 있을 것 같은데 방법을 모르겠네요 ㅋㅋ 특히 마지막에 세 수 중 가장 큰 값 찾는거 ...
> [5주차] PYTHON: 모의고사

- programmers/unanchoi/bf/소수찾기.py
https://school.programmers.co.kr/learn/courses/30/lessons/42839
- 소수 찾기는 에라토스테네스의 체 (n-1까지 검사해도 시간 초과 안나네요 ㅋㅋ)
- 공간복잡도 :  O(N)
- 예외 상황을 빠르게 파악하지 못해서 문제 풀이 하는데 시간이 꽤 걸렸습니다 ~
> [5주차] PYTHON: 소수 찾기

- programmers/unanchoi/bf/최소직사각형.py
https://school.programmers.co.kr/learn/courses/30/lessons/86491
- Bruteforce
- 큰 값과 작은 값을 기준으로 한 번씩 생각해주면 되는 문제 였다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 처음에 가로, 세로 길이를 모두 바꿔가면서, 대입해보는 코드를 작성하면서 많이 삽질했는데 ...문제를 천천히 잘 읽어보는 연습이 필요한 것 같습니다.
> [5주차] PYTHON:  최소직사각형

- programmers/hellozo0/bf/최소직사각형.java
주어진 직사각형들을 담을 수 있는 최소사이즈의 직사각형틀의 크기를 구하는 문제
정렬이 중요하다 생각을 했다. - 정렬을 하는 기준이 있어야했다.
완전 탐색 문제
1. 먼저 2차원 배열의 요소들 끼리의 오름차순 정렬
2. 그다음 [0] 인덱스의 요소들끼리의 정렬을 통해 정렬 
- 시간복잡도 : O(nlog(n)) -> sort 메소드
- 공간복잡도 : O(n^2) -> 주어진 입력값의 2차원 배열 
지금 이거 쓰면서 생각이 든건데 
굳이 for문으로 [0] 인덱스의 것 까지 max 찾아내지 않아도 그냥 [1]인덱스의 요소만 max 찾아도 되는 문제인데... 
굳이 불필요한 코드가 늘었다...
> [5주차] JAVA : 최소직사각형

- programmers/hellozo0/bf/망한소수찾기.java
- programmers/hellozo0/bf/소수찾기.java
주어진 숫자 카드들을 조합해서 만들 수 있는 소수의 개수 구하기
음 일단 순열을 구해야겠다 생각을 했고,,, 그 요소에 대해 각각 소수 판별해서 소수라면 map에 넣는 식으로..?
map을 쓴 이유는 011 이 있을 경우 01 01 두개의 조합이 나오기 땨뮨에 map으로 중복 제거 해줘야 했음!
에라스토스 체? 맞나 소수 알고리즘과 순열 알고리즘 사용
1. String을 char 배열로 변형
2. 그 각 요소에 대해 조합을 만든다. (처음에 아무 생각없이 조합만 생각해서 틀렸음 - > 꼭 순열 알고리즘 사용해야함)
3. 그리고 각 조합이 소수면 map에 추가 ( 중복 제거를 위해)
4. 그리고 map의 size를 return
- 시간복잡도 : n! 일듯 합니다... -> 순열 때매?
- 공간복잡도 : n
처음에 조합으로 풀다가 1,7의 경우 1,7,17만 나오길래... 71이 나와야하는데 그래서
순열로 다시 풀었삼
근데 순열 알고리즘 이해가 안가요 좀 더 알아바야할듯 문제 푸는 방법은 알았는데 해당 알고리즘이 익숙치 않았슴
> [5주차] JAVA : 소수찾기

- programmers/hellozo0/bf/모의고사.java
완탐
딱 그냥 하나하나 먼저 계산해봐야겠다 생각했다.
노가다 완전 탐색
1. 하나하나 값 비교해서 맞으면 개수를 다 따로 센 다음 최대값을 구한다
2. 최대값이랑 같은 요소들을 찾으면 끝
- 시간복잡도 : O(n)..?
- 공간복잡도 : O(n)...?
효율적인 방법이 없을까..... 넘 노가다스
> [5주차] JAVA : 모의고사

- programmers/hellozo0/bf/카펫.java
완탐
타일의 개수와 가로세로의 규칙을 찾으면 되겠다 생각을 해서 짱구 열시미 돌려서 찾음
완전탐색 , 규칙 찾아야함
가로 세로, 노랑 갈색의 개수 로직 만 잘 계산하면 된다
- 시간복잡도 : O(n) -> 정확히는 n/2
- 공간복잡도 : O(n)
로직이 복잡하다 , 넘 피곤해서 삼중 if문을 써버렸는데 더 좋은 방법 이 잇을듯 하다..하지만..지금은 생각하기 싫다...피곤해...
> [5주차] JAVA : 카펫

- programmers/hellozo0/bf/전력망_둘로_나누기.java
어느 부분을 잘라서 노드들의 개수 차이가 적게 나게끔... 자른다.. 개수 차이가 가장 적게 나는 수는?
어찌 푸는지 모르겠어서 구를ㅇ이...dfs bfs인데...
bfs, dfs
구선생의 도움 하에 
1. 어느 부분을 다 잘라보고 차이를 매번 다 계산한다. --> 근데 코드를 이해 못하겠음 
- 시간복잡도 :  O(n) -> dfs, bfs 시간 복잡도
- 공간복잡도 :  O(n^2)
dfs, bfs 문제 일단 뭐를 선택해야하는지 못 고른다.
그리고 dfs bfs 잘 모른다...
어떻게 풀어야할지.. 알겠는데 구현을 못하겠는거
>  [5주차] JAVA : 전력망을 둘로 나누기

- programmers/hellozo0/bf/피로도.java
주어진 조건에 따라 몇개의 던전을 최대한 많이 할 수 있는 가~
dfs
dfs
모든 경우를 다 탐색해서 , 최대값을 구한다...
- 시간복잡도 : O(n^2) --> dfs...? 재귀..?
- 공간복잡도 : O(n^2) -> 주어진 함수가 2차원 배열임
Math.max(count, depth) 하는 부분을 미처 생각하지 못했다. ...어려븐것..
> [5주차] JAVA : 피로도

- programmers/hellozo0/bf/모음사전.java
주어진 문자의 번째 숫자를 알아내기
재귀.....
완탐
1. 모든 사전 set을 만든다
2. 그리고 주어진 문자가 몇번째 인덱스인지 알아낸다
- 시간복잡도 : 재귀를 써서 n^2인데, 숫자가 정해져 있어서... 음엄..모르겠어요
- 공간복잡도 : O(5*5* 5* 5*5)인듯요
아 다 만들고 비교하는거 디게 비효율적인거 같아요 더 좋은 방법은 찾지 못했다고 한다/...
구글링 해보니 해당 번째 숫자들이 바뀌는 term을 가지고 비교했던데 그게 최선일랑가
> [5주차] JAVA : 모음사전

- programmers/Hong0329/bf/week5-1(FIX).cpp
- programmers/Hong0329/bf/week5-1.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/86491
* 가로 세로 중에 큰 값들을 한 쪽으로 몰아서 그 중에 큰 값, 그리고 다른 쪽 중에서 가장 큰 값을 곱한다.
* 완전 탐색
* 가로, 세로라는 벡터를 임의로 하나씩 만든다.
* 입력받은 값들에 대해서 for문을 돌면서 각 값의 두 값 중에 큰 애를 가로라고 임의로 설정하고 작은 애는 세로로 설정한다.
* 가로 세로 벡터를 sort한 후에 가장 마지막에 있는 값들끼리 곱하면 답이 된다.
---
* PR을 적으면서 더 간단한 방법이 떠올라서 새로 코드를 작성하고 FIX로 추가했습니다.
* 위와 로직은 같으나 새로 벡터 공간을 할당하지 않고 그냥 각 값에 대해서 크기 비교를 하였습니다.
- 시간복잡도 : O(nlogn) => O(n)
- 공간복잡도 : O(n)
* 두 개의 벡터를 새로 만들면서 너무 공간을 많이 썼나 싶은 생각이 있다.,,, 차피 for문을 도니까 각 값에 대해서 최댓값만 들고 다니면서 탐색할 수 있을 것 같은데...벡터로 해버리는게 편해서 이렇게 했다...
---
* 벡터가 편하고자시고가 아니라 시간 복잡도와 공간 복잡도가 모두 줄어드는 코드로 수정했다....
> [5주차] C++ : 최소직사각형

- programmers/Hong0329/bf/week5-2.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42840
* 3명의 규칙에 따라 맞은 문제 수를 구한 후에 가장 많이 맞은 사람을 찾아내기
* 완전 탐색
* 5,8,10개 단위로 돌아가는 규칙을 다 저장해놓고, 입력 받은 값을 각 단위로 나눈 나머지값을 이용하여 정답인지 오답인지 판단한다.
* 판단한 값들을 벡터에 넣고 가장 큰 값을 찾은 후에 앞에서부터 해당 값과 같은 벡터값의 인덱스 + 1을 정답 벡터에 집어 넣는다.
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
코드가 좀 지저분한 느낌이다....
> [5주차] C++ : 모의고사

- programmers/Hong0329/bf/week5-3.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42839
* next_permutation과 substr을 통해서 모든 경우를 다 체크한다.
* 완전 탐색
* next_permutation과 substr을 통해서 모든 경우를 다 체크한다.
* 항목을 저장하는 자료구조를 set을 사용하여 중복을 자동으로 처리되게 한다.
- 시간복잡도 :O(n^2) -> 이때 n은 주어진 numbers의 길이
- 공간복잡도 : O(n)
* 없습니다.
> [5주차] C++ : 소수찾기

- programmers/Hong0329/bf/week5-4.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42842
* 처음에는 에제만 보고 대충 생각해서 제곱근을 기준으로 위 아래 정수 중에 약수인 애들이 정답일거라 생각했었음
* 완전 탐색
* 높이를 변수로 두고 for문을 돌면서 전체 타일의 개수가 나누어졌을 때, 가로 세로 * 2 -4 한 개수가 갈색 타일 개수이면 정답으로 출력
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
* 처음에 문제를 대충읽고, 에제로만 검증한 점.....
> [5주차] C++ : 카펫

- programmers/Hong0329/bf/week5-5.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/87946
* next_permutation을 이용한 완전 탐색
* 완전 탐색
* next_permutation을 이용하여 모든 던전 순서에 대해서 돌아보고 그 중 가장 많이 던전에 들어간 수를 출력한다.
- 공간복잡도 : O(n)
* dfs로 풀 수 있을 것 같은데 급해서 완탐으로 돌렸다...
> [5주차] C++ : 피로도

- programmers/Hong0329/bf/week5-7.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/84512
* 만들어지는 규칙이 dfs랑 같아서 dfs를 이용하자.
* dfs + 완전탐색
* aeiou문자열에 대해서 dfs를 돌리면 a->aa->aaa ~ , 문제에서 말한 규칙과 같이 생긴다.
* 때문에 문자열 길이 5에만 제한을 두고 돌리면서 cnt를 늘려가면 입력받은 단어가 몇 번째에 나오는지 알 수 있다.
- 시간복잡도 :5^5?
- 공간복잡도 : 1 + 5 + 25 + 125 + 625 + 3125
* 시간 복잡도와 공간 복잡도가 확신있게 게산이 안된다....
> [5주차] C++ : 모음사전

- programmers/hellozo0/greedy/섬_연결하기.java
섬 연결해서 최소비용 구하기
딱 봐도 트리 구조... union find 떠오름
크루스칼 
1.  연결이 안되어 있다면 연결해주기
2. 연결 되어 있다면 pass 
3. 이것만 잘 기억하고 union-find 로직만 기억하면 ok
(간선 수가 적을때는 크루스칼, 아니면 프림을 쓰면 된다고 한다)
- 시간복잡도 : O(nlogn) -> 크루스칼의 ...시간 복잡도는 상수라고 한다 따라서 정렬이 가장 큰 시간 복잡도..!
- 공간복잡도 : O(n) -> 입력크기가 3n
음 프림은 풀줄 모른다..^_6...ㅠ
> [6주차] JAVA : 섬 연결하기

- programmers/hellozo0/greedy/단속카메라.java
약간 이전의 디스크 컨트롤러? 그 문제랑 비슷한듯...
정렬을 어디를 기준으로 할것인가  + 어떻게 자를 것이냐....
일단 정렬을 해야 했다 처음에는 들어오는 시점을 기준으로 해야하나 했는데 나가는 시점을 기준으로 해야 헸다
그리고 나서 그 밖에 범위에 있는 값의 들어오는 시점과 비교하기
정렬, 그리디
1. 나가는 시점으로 정렬
2. 그리고 순서대로 지나가다가 들어오는 시점이 더 크다면 갱신~ 그리고 줄 하나 그었다고 생각하기 
- 시간복잡도 : O(nlogn) -> 정렬
- 공간복잡도 : O(1)? O(n) -> 입력한 값이 2차원 배열(그치만 요소 2개라서 2n)이니까.... n 인가..? 내가 쓴것은 1만큼... 
줄을 긋는 시점을 이미 긋고 다음거랑 비교한다는 생각을 미처 하지 못했다..
> [6주차] JAVA : 단속카메라

- programmers/hellozo0/greedy/구명보트.java
2명만 탈 수 있는 구명보트에 최소한의 보트만 가져가려고 할때 보트의 수
처음에는 오름차순 정렬하고 그냥 작은 것들 부터 묶어서 나가려고 했는데 아니였다.
나중에 되면 뒤로 가면 거의 대부분의 확률로 1개씩 타야하는 문제가...
따라서 가장 작은 값 가장 큰 값을 묶어서 가야했던 문제..
그리디
문제 분석과 동일 
- 시간복잡도 : O(nlogn) -> sort 
- 공간복잡도 : O(1) -> 변수만 씀
min, max 끼리 묶이는 테스트 케이스를 생각 못한것.... 첨에 뭔 풀ㅇ렀는데 0점 나와서 ㅋㅋㅋㅋ 아....ㅎㅎ^^
> [6주차] JAVA : 구명보트

- programmers/hellozo0/greedy/체육복.java
체육복을 2개 가져오거나 1개 가져오거나 안가져오는 경우가 있는데
서로 앞 뒤 번호에만 체육복을 빌려 줄 수 있다. 그럴 경우 체육복 입은 인원의 수는?
그냥 if문으로 케이스를 나눴다
그리디
케이스를 잘 분리하는게 중요한거 같다.
1. 따라서 1개 가져온애, 2개 가져온애 0개 가져온애 잘 나눈다. ( 나는 배열에 012 값으로 설정)
2. 그리고 앞에 애에 빌려 주는 경우 뒤에 빌려주는 경우 if문으로 나눠서,.... 계산
- 시간복잡도 : O(nlogn) -> sort 함수를 써서 그렇다 
- 공간복잡도 : O(n) -> 배열 하나 씀 >< 
첨에 틀렸는데 아마 정렬을 안해서 그런거 같다는 생각을 했다... 주석으로 된 코드는 틀린 코드다
그리고 2개 있는경우도 잘 생각해서 개수에 포함해야했는데 놓쳤다
> [6주차] JAVA : 체육복

- programmers/hellozo0/greedy/조이스틱.java
조이스틱을 사용해 알파벳을 조건에 맞게 변경하는데 걸리는 횟수
왼쪽으로 가는 경우에 대한 식을 잘 세워햐한다.....
그리디
1. 그냥 오른쪽으로 쭉 이동하는경우와 
2. 왼쪽으로  이동하는경우 를 계산 하는 수식중에 가장 작은 값을 return
- 시간복잡도 : 최악의 경우 n x n-1 번 해서 O(n^2)가 될 수도 있겠다
- 공간복잡도 : O(1)
로직 미쳤다 min 어떻게 함 ~....아.,....
> [6주차] JAVA : 조이스틱

- programmers/Hong0329/bf/week5-6.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/86971
* 이건 dfs를 써야겠다...
* dfs와 완전 탐색
* 입력받은 간선의 관계들을 이차원 배열에 옮겨서 양방향으로 정리해놓는다.
* 간선을 하나 자르고, 모든 곳에서 dfs를 돌려서 나오는 2개의 값을 vector에 저장한다.
* 그 두 값이 나눠진 구역에 있는 송전탑의 개수이므로 둘의 차이의 절대값의 최소값을 저장한다.
* 이전 문제도 이렇게 dfs를 사용하면 시간 복잡도가 개선될 여지가 있을 것 같은데 좀 더 생각해봐야겠다.
> [5주차] C++ : 전력망을 둘로 나누기

- programmers/Hong0329/greedy/week6-1.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42862
* 앞에서부터 하나하나 탐색해간다.
* 그리디
* 체육복이 없는 사람은 -1, 있으면 0, 여분이 있으면 1로 설정해놓는다.
* 앞에서부터 앞뒤 학생의 체육복 상태를 확인해가며 현재 보는 학생이 필요하고 앞이나 뒤에 체육복이 있으면 빌려온다.
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
* 없습니다.
> [6주차] C++ : 체육복

- programmers/Hong0329/greedy/week6-2.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42860
* 모든 경우를 다 봐야하는데 어떻게 볼 수 있을까?
* 그리디
* 일단 알파벳이 바뀌는 것들에 대해서는 check함수를 따로 만들어서 처리했다.
* 이제 알파벳을 이동하기 위해서 사용하는 조이스틱의 횟수를 구해야한다.
* 아 부분은 구글링을 통해서 해결했다....왼쪽으로 쭉 움직이는 경우 오른쪽으로 쭉 움직이는 경우, 특정 철자에서 다음 A가 아닌 철자까지 이동할 때 뒤로 움직여서 가는 경우, 처음부터 뒤로 갔다가 앞으로 다시 오는 경우 => 총 이렇게 4가지 경우가 있다.
* 위의 4가지 경우를 모두 상황에 맞춰서 따져보고 그때그때의 최소값을 저장한 후에 마지막에 그 최소값을 answer에 더해준다.
- 공간복잡도 : O(n)
* 이동에 대한 횟수를 구하는 건 결국 구글링을 통해서 알게되었다...
> [6주차] C++: 조이스틱

- programmers/Hong0329/greedy/week6-3.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42883
* 상황에 맞춰서 경우를 다 따져보자. 앞의 수가 클수록 큰 수가 된다.
* 그리디
* 삭제할 수 있는 개수 만큼을 뒤에서 제외하고 남은 글자수들 중에 가장 큰 수가 답에 포함되는 것이 가장 큰 수를 만드는 법이다.
* 그 다음에 답에 포함될 수를 구하는 것은 방금 앞에서 선택한 수보다 뒤에 있는 수들 중에 가장 큰 수를 고르는 것이 최적해를 만드는 법이다.
- 공간복잡도 : O(n)
* 아이디어가 바로바로 생각나지 않았다....
> [6주차] C++ : 큰 수 만들기

- programmers/Hong0329/greedy/week6-4.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42885
* 보트에 최대 2명이니까 가장 무거운 아이와 가벼운 아이를 짝지어보자
* 그리디
* 크기 순으로 정렬한 후에 가장 무거운 아이와 가벼운 아이를 짝지어본다.
* 짝지었을 때 limit을 넘지 않으면 둘이 가능한 것이고, 아닐 경우 무거운 아이는 그 누구와도 같이 보트를 탈 수 없다는 말이 된다.
- 공간복잡도 : O(n)
* 없습니다.
> [6주차] C++ : 구명보트

- programmers/Hong0329/greedy/week6-5.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42861
* 전형적인 크루스칼 알고리즘 문제
* 크루스칼(그리디)
* 간선들을 코스트 기준으로 정렬한 후에 작은 비용부터 따져나간다.
* 양 끝이 결국엔 연결된다면, 즉 노드들 사이에 사이클이 생긴다면 불필요한 간선이므로 넘어간다.
- 공간복잡도 : O(n^2) 이때 n은 섬의 개수
* 크루스칼인 것은 알았으나 구현에 조금 시간이 걸린점 -> 연습하자...
> [6주차] C++ : 섬 연결하기

- programmers/Hong0329/greedy/week6-6.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42884
* 정렬 후에 앞에서부터 조건을 따져보자
* 그리디
* 진입하는 순서대로 정렬한 후에 앞에서 부터 겹치는 부분을 계산해본다.
* 다음 차량이 애초에 진출한 후에 진입하면 카메라가 더 필요한 것이고, 만약 앞 차의 진출 보다 진입이 빠르다면 해당 차량의 진입시점으로 카메라를 옮겨서 생각한다.
- 공간복잡도 : O(n)
* level3이라서 너무 쫄았다...
> [6주차] C++ : 단속카메라

- programmers/sung-silver/greedy/week6-1.java
- 체육복: https://school.programmers.co.kr/learn/courses/30/lessons/42862
- 앞 뒤로 빌려줄 수 있는 애들에 대해 검사하여 빌려줄 수 있으면 빌려주자!라는 생각이 들었음
- 그리디라고 써져있지만 단순 구현같기도하구
- 체육에 참여할 수 있는 사람의 최소를 0으로 설정하고 여벌이 있으면 1, 체육복을 잃어버렸으면 -1로 값을 설정한 후 -1인 경우에 앞 뒤를 검사하여 체육복을 빌릴 수 있는지 확인한다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 그리디..인가?
> [6주차] JAVA: 체육복

- programmers/sung-silver/greedy/week6-2.java
- 큰 수 만들기
- 어떻게해야 가장 큰 수가 남을까?
- 그리디
- 가장 큰 수가 되야한다 + 보장해야 할 자릿수의 개수가 전체 문자열 - k개 이다 라는 조건 생각하기
- 공간복잡도 : O(N)
- 그리디는 운인거 같기도하고..
> [6주차] JAVA: 큰 수 만들기

- programmers/sung-silver/greedy/week6-3.java
- 구명보트: https://school.programmers.co.kr/learn/courses/30/lessons/42885
- 두명씩 태우니까 가장 큰 값과 가장 작은 값을 태울 수 있을때가 효율적일 것이다
- 그리디
- 오름차순으로 정렬 후 앞뒤에서 min, max로 짝지어 2명씩 태우자
- 공간복잡도 : O(N)
- 문제를 제대로 안읽어서 2명씩 태운다는 말을 못봤다 ^^.. 그래서 놀라운 점수를 처음에 받았음
> [6주차] JAVA: 구명보트

- programmers/sung-silver/greedy/week6-4.java
- 조이스틱: https://school.programmers.co.kr/learn/courses/30/lessons/42860
- 어떻게 최소로 움직일까?
- 그리디
- 상하로 움직이는 부분을 더한다
- 연속되는 A의 개수를 확인한다
- 이동 수가 적은 방법을 선택한다
- 공간복잡도 : O(N)
- 이동의 최소 거리를 구하는 방법에 대해 생각하는 방법을 알아내는 것이 이해가 잘 안되었음
- 여러 블로그를 보다보니 뒷쪽부터 조작하는 것이 더 적은 이동 횟수를 가져갈 수 있다는 점도 아래 블로그를 통해 알게 됨
- https://velog.io/@jeeseob5761/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%A1%B0%EC%9D%B4%EC%8A%A4%ED%8B%B1
> [6주차] JAVA: 조이스틱

- programmers/sung-silver/greedy/week6-5.java
- 단속카메라: https://school.programmers.co.kr/learn/courses/30/lessons/42884
- 카메라가 최소로 필요하려면..?
- 그리디
- 아래 사진처럼 끝나는 지점을 기준으로 오름차순 정렬
- 앞에서부터 끝나는 지점에 카메라 설치 -> 비교하는 것은 시작 지점이 이전에 설치된 카메라 시점보다 큰가? 크다면 카메라를 새로 설치해야 찍힌다
- 시간복잡도 : O(NlogN)
- 공간복잡도 : O(N)
- Lv2보다 이게 더 쉬웠음..?
> [6주차] JAVA: 단속카메라

- programmers/sung-silver/greedy/week6-6.java
- 섬 연결하기: https://school.programmers.co.kr/learn/courses/30/lessons/42861
그래프 그래프 그래프....
- 그리디
- 그래프의 간선들을 가중치 기준 오름차순으로 정렬한다.
- 정렬된 간선 리스트를 순서대로 선택하여, 간선의 정점들을 연결한다. 이때 정점을 연결하는 것은 Union-Find의 Union으로 구현한다.
- 만약 간선의 두 정점 a,b가 연결되어 있다면 스킵한다.
- 위의 과정을 반복하여 최소 비용의 간선들만 이용하여 모든 정점이 연결된다.
- 시간복잡도 : O(ElogE)
- 공간복잡도 : O(n)
- 그래프를 몰라서.. 미치겠네요 하하 겨우 이해했는데 이게 진짜 LV3 수준인듯 제기준..
> [6주차] JAVA: 섬 연결하기

- programmers/unanchoi/greedy/체육복.py
https://school.programmers.co.kr/learn/courses/30/lessons/42862
- Greedy
- lost, reserver를 오름차순으로 정렬한 뒤에 1 작은 수가 해당되는지 체크하는 형태로 코드를 작성하면 최댓값을 구할 수 있음.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 잃어버린 사람이 나눠주는 케이스를 고려하지 못하여, 시간이 오래걸렸다.
> [6주차] PYTHON: 체육복

- programmers/unanchoi/greedy/조이스틱.py
https://school.programmers.co.kr/learn/courses/30/lessons/42860
- 그리디
- 각 인덱스에서 최소로 움직이는 상황을 계산해서 Answer에 더해준다.
- 
- 시간복잡도 : O(N) ? 
- 공간복잡도 : O(N)
- 문제 논리 자체는 이해했는데, 식을 어떻게 세워야할지 어려웠다.
> [5주차] PYTHON: 조이스틱

- programmers/unanchoi/greedy/구명보트.py
https://school.programmers.co.kr/learn/courses/30/lessons/42885
- 그리디
- 정렬 후에 가장 무거운 보트와 가장 가벼운 보트의 무게 두 개의 무게를 더해서, limit와 비교하면서
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
> [5주차] PYTHON: 구명보트

- programmers/unanchoi/greedy/단속카메라.py
https://school.programmers.co.kr/learn/courses/30/lessons/42884
- 그리디
- 진출 시점으로 정렬하고, 진출시점이 가장 빠른 것부터 카메라의 위치와 비교하여, 카메라의 위치보다 큰 경우에 카메라를 업데이트한다.
- 공간복잡도 : O(N)
- 로직을 생각하는 것이 너무 어려워서 다른 코드를 참고했습니다... 코드는 짧은데 아이디어가 어려웠습니당
> [5주차] PYTHON: 단속카메라

- programmers/unanchoi/greedy/큰수만들기.py
https://school.programmers.co.kr/learn/courses/30/lessons/42883
- 그리디
- index를 돌면서, 현재 수 뒤로 작은 수 들을 
- 공간복잡도 : O(N)
- 쉽게 풀 수 있는 문제인데, 복잡하게 계산해서 푸는 방향으로 풀었다 ..
> [5주차] PYTHON:  큰수만들기

- programmers/hellozo0/dp/등굣길.java
등교길의 경우의수를 구하는 문제
음.... 누적합..? 경우의수..! 
dp
1. 먼저 문제 설명에  n,m 반대로 되어 있어서 flip 하고 생각해야하고,,, 안해도 그만~ 
2. 경우의 수 문제라 다 1이라고 전제로 두고 웅덩이랑 합하면 그냥 1 way, (웅덩이는 -1로 세팅해둔다 그래야지 웅덩이인걸 구별하니까)
3. 그래서 위또는 왼쪽이 웅덩이 일경우 그것을 빼고 더하는 식으로 누적합~
nothing
> [7주차] JAVA : 등굣길

- programmers/hellozo0/dp/사칙연산.java
()를 적절하게.... 조건에 맞게 넣어서 나온 값 중에 가장 큰 값 구하기
분석하지 못햇다..^_^ 어렵다 어떻게 조건을 나눠야하는지 조건식을 못 떠올렸따
dp
뭔가 아이디어로는 a+b a-b -(a+b) -(a-b) 연산의 조건을 잘 생각해서 푸는것인데...
더 생각해봐야지
- 시간복잡도 :
- 공간복잡도 :
뿅 내일 더 봐야할 문제~!
> [7주차] JAVA : 사칙연산

- programmers/hellozo0/dp/도둑질.java
원형 형태의 집 이 있고, 바로 연달아 옆집을 털수 없을 경우 턴 가격의 최대값
dp로 첫집을 턴 경우와 아닌 경우로 나눔
dp
음 max로 비교해가몀서 최대 턴 가격을 바꿔간다
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
>  [7주차] JAVA : 도둑질

- programmers/Hong0329/dp/week7-1.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42895
* 사용하는 N의 개수로 DP식을 짜야겠다 -> 최솟값이 8보다 크면 -1을 return 하라는 조건이 나에게는 힌트였다.
* DP
* set자료구조를 사용하여 인덱스 값은 사용하는 N의 개수로 잡고, 거기서 나올 수 있는 연산값들을 이전 값들을 사용하여 저장한다.
* 저장한 후에 문제에서 주어진 숫자가 set에 포함되어있다면 그 당시의 인덱스 값을 답으로 출력
- 시간복잡도 :O(....어렵다...모르겠다...)
- 공간복잡도 :O(8*7*4)
* 시간복잡도가 계산이 안된다.....
> [7주차] C++ : N으로 표현

- programmers/Hong0329/dp/week7-2.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/43105
* 삼각형에서 위 아래 더해지는 것을 부분으로 보면서 DP식을 세운다.
* DP
* 아래서 부터 위에 더해지는 것 중에 큰 값을 더해나간다.
* 업습니다.
> [7주차] C++ : 정수 삼각형

- programmers/Hong0329/dp/week7-3.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42898
* 가는 방법의 개수를 위에서 내려오는것, 왼쪽으로 오른쪽으로 넘어오는 이 2가지 방법을 저장해간다.
* DP
* i와 j를 길의 위치로 잡고, 해당 값을 그 위치까지 올 수 있는 방법의 수로 만든다.
* 이때 오는 방법은 최소의 경로이므로 위에서 아래, 왼쪽에서 오른쪽으로 이동하는 2가지 방법밖에 없다.
- 시간복잡도 :O(n*m)
- 공간복잡도 :O(n*m)
* 없습니다.
> [7주차] C++ : 등굣길

- programmers/Hong0329/dp/week7-4.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/1843
* 처음에는 괄호가 생길 수 있는 경우에 따라 다 구하려고 했으나 불가능함을 느낌...
* DP
* 구글링을 통해서 풀이 방식을 배웠습니다...구현하는 것조차 어렵네요,,,,
* +와 -를 기준으로 해당 위치에서 나올 수 있는 최대값과 최소값을 저장해나가는 방식
- 시간복잡도 : 
- 공간복잡도 :
* 정말정말 매우매우 어렵네요....
> [7주차] C++ : 사칙연산

- programmers/Hong0329/dp/week7-5.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42897
* 1차원 DP테이블을 만들고, 인덱스는 집의 순서, 해당값은 그 위치까지 가지고 올 수 있는 금액의 최대값
* DP
* 2번의 DP를 돌린다.
* 처음은 첫번째 집을 도둑질 하는 경우
* 다음은 첫번째 집을 도둑질하지 않는 경우
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
* DP어렵네요...좀 더 연습해야겠습니다...이번에도 코드 참고...ㅜ
> [7주차] C++ : 도둑질

- programmers/sung-silver/dp/week7-5.java
- 사칙연산: https://school.programmers.co.kr/learn/courses/30/lessons/1843
- 괄호를 어디에 넣을까?
- dp
- https://velog.io/@kamo0915/Java-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%82%AC%EC%B9%99%EC%97%B0%EC%82%B0-4%EB%8B%A8%EA%B3%84
- 이거를 진짜 많이 봤습니더...
- 시간복잡도 :
- 공간복잡도 :
- 같은 LV4인데 왜이렇게 난이도가 다른지....
- 좀 더 공부하고 제 힘으로 풀고 인증 남길게염..
> [7주차] JAVA: 사칙연산

- programmers/sung-silver/dp/week7-4.java
- 도둑질: https://school.programmers.co.kr/learn/courses/30/lessons/42897
홀수 인덱스, 짝수 인덱스로 나누어서 계산하기?
- DP
- 처음 집 훔치고 마지막 집은 훔치지 않는 케이스
- 처음 집을 훔치지 않고 마지막 집을 훔치는 케이스
- 이렇게 케이스를 나누어 진행한다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 선형 배열로만 생각하다보니 처음에 처음집과 마지막 집이 이어져있다는 것을 놓쳤음..
- 또한 같은 LV4인데 이거는 괜찮고 사칙연산은 너무 힘들다..
> [7주차] JAVA: 도둑질

- programmers/sung-silver/dp/week7-3.java
- 등굣길: https://school.programmers.co.kr/learn/courses/30/lessons/42898
- 경우의수..같은 느낌
- dp
- 배열에 값을 update하며 해당 우ㅣ치까지 갈 수 있는 경우의 수를 저장
- (1,1)를 (0,0)으로 둬서 틀렸었음.. 그림이 애매해 ㅡㅡ
> [7주차] JAVA: 등굣길

- programmers/sung-silver/dp/week7-2.java
- 정수삼각형: https://school.programmers.co.kr/learn/courses/30/lessons/43105
- 누적합을 구하는데, 최대가 될 수 있는 요소만 선택한다!
- dp
- 삼각형의 위치별 최대값을 저장할 배열 생성
- 삼각형의 가장 왼쪽은 누적합을 구한다
- 배열로 표현했을 때 가장 왼쪽의 값은 바로 위에서 더해 내려오는 값이 최대
- 왼쪽 위에서 내려와 더했을 때: dp[i-1][j-1] + triangle[i][j]
- 오른쪽 위에서 내려와 더했을 때: dp[i-1][j] + triangle[i][j]
- dp의 공간을 할당할 크기를 정하는데 순간 당황했었다
- 이차원 배열의 길이가 높이와 같다는 것을.. 바로 떠올리지 못했다 ㅋ..
> [7주차] JAVA: 정수 삼각형

- programmers/unanchoi/dp/등굣길.py
https://school.programmers.co.kr/learn/courses/30/lessons/42898
- DP
-  물에 빠진 곳을 표시하고, DP로 최단 경로 계산
- 시간복잡도 : O(N)
- 2차원 문제는 어렵다 ..
> [PYTHON] 등굣길

- programmers/unanchoi/dp/N으로표현.py
https://school.programmers.co.kr/learn/courses/30/lessons/42895
- 1 ~ N인 각 경우에서 나올 . 수있는 수를 만든 후에 목표 숫자를 반환한다
처음에 캐시를 잡는 것이 어려웠다 ..
> [7주차 Python:  N으로 표현

- programmers/unanchoi/dp/사칙연산.py
https://school.programmers.co.kr/learn/courses/30/lessons/42897
- 
- DP
- 첫번쨰 집 훔치는 경우와 첫번쨰 집을 안훔치는 경우를 
- 어려워서 .. 풀이를 참ㅁ고했습니다.. 레벨 4는 어렵네요
> [7주차]  Python 도둑질

- programmers/sung-silver/week8-1.java
- 타겟넘버: https://school.programmers.co.kr/learn/courses/30/lessons/43165
- 더하거나 빼거나를 할 수 있다
- DFS, BFS
- 나는 DFS로 풀었음
- 재귀함수를 사용하여 더하거나 빼는 경우의 수에 대한 계산결과를 구하면서 target 넘버가 되는 개수를 센다
- 시간복잡도 : 재귀함수의 시간복잡도는 어렵다.. 그러나 n개의 수가 주어질 때 각각을 더하고 빼는 것이므로 O(2^n)
- 공간복잡도 : O(n)
- 재귀 호출 시 함수가 호출되면 스택영역에 메모리가 할당될텐데, 이것은 고려 안해도..되나? 
- location++로 코드를 작성하면 location+1인 값을 dfs 함수에 넘기는 것이 아니라 함수 호출 이후에 location 값이 증가되는데, 이를 놓쳐서 조금 헤맸다
> [8주차] JAVA: 타겟넘버

- programmers/sung-silver/dfs-bfs/week8-2.java
- 네트워크: https://school.programmers.co.kr/learn/courses/30/lessons/43162
- 탐색을하며 방문한 노드들을 체크하기
- dfs, bfs
- Set(visited)을 이용해서 방문한적이 있는지를 확인한다
- HashSet을 사용하여 요소를 찾는데 O(1) 시간이 걸린다 
- visited에 방문한 기록이 없으면 추가하고 그것과 연결된 노드들에 대하여 탐색을 계속 진행한다
- 탐색이 끝나면 같은 네트워크 망으로 생각하고 answer를 1 증가한다
- 공간복잡도 : O(N)
- 아직 어렵다..
> [8주차] JAVA: 네트워크

- programmers/sung-silver/dfs-bfs/week8-3.java
- 게임 맵 최단거리: https://school.programmers.co.kr/learn/courses/30/lessons/1844
- BFS로 생각
- BFS: 시작 지점에서 가까운 노드부터 차례대로 탐색하는 알고리즘으로 최단경로 문제를 풀 때 효과적
1. (0, 0) 노드는 큐에 삽입
2. 큐에서 노드를 꺼내 해당 노드의 인접 노드 중에서 벽이 아니고 아직 방문하지 않은 노드가 있다면 삽입해주고 카운트 + 1
3. 큐에 더이상 탐색할 노드가 없을 때까지 반복해주다가 상대방 진영에 도달했을 때 카운트값을 return
- 그래도 BFS로 식은 세웠다!
- 처음에 상하좌우에 대해 표현할 때 if를 여러번 썼는데, 상하좌우에 더할 값을 저장하는 배열과 for문을 사용하여 표현하니 코드의 가독성이 더 올라간 것 같아 수정했다. -> 이런 센스를 기르고싶음
> [8주차] JAVA: 게임 맵 최단거리

- programmers/Hong0329/dfs-bfs/week8-2.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/43162
* 모든 정점에 대하여 dfs(이미 방문했다면 스킵)
* dfs
* 모든 정점에 대하여 연결된 정점들을 방문한다.
* 방문할때마다 방문 여부를 체크한다.
* 특정 정점으로부터 더이상 연결된 정점이 없다면 answer++
- 공간복잡도 : O(n)
* 없습니다.
> [8주차] C++ : 네트워크

- programmers/Hong0329/dfs-bfs/week8-3.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/1844
* BFS탐색
* BFS
* BFS를 사용하여 출발지 노드로 부터 모든 노드들까지의 최단 경로를 체크한다.
* BFS오랜만에 코드짜려니까 머리가 안돌더라구요...익숙해지기
> [8주차] C++ : 게임 맵 최단거리

- programmers/unanchoi/bfsdfs/게임맵최단거리.py
https://school.programmers.co.kr/learn/courses/30/lessons/1844
- bfs, dfs
- 제한 사항에 맞춰서, 순회하며 얼마나 움직여야 되는지 찾는다.
- 공간복잡도 : O(N)
- 풀이가 어려워서 .. 찾아봤습니다. 너무 dfs, bfs 함수 만들어서 풀려고만 생각함.
> [8주차] PYTHON: 게임 맵 최단거리

- programmers/unanchoi/dfsbfs/타겟넘버.py
https://school.programmers.co.kr/learn/courses/30/lessons/43165
Dfs
숫자를 더하는 경우와 빼는 경우를 고려하여, dfs 계산
- 공간복잡도 : O(N)
- 계산 식을 빠르게 떠올리지 못한 것 ?
> [8주차] PYTHON: 타겟넘버

- programmers/hellozo0/dfs-bfs/타겟_넘버.java
주어진 numbers를 조합해서 target을 만들 수 있는 가지수 구하기
재귀로 모든 방법 탐색하려고 했다.
dfs/bfs
재귀로 계속 반복
- 시간복잡도 : ..어라라 음암.. 재귀인데 그러면 n^2일라나
- 공간복잡도 : O(n)
재귀말고 다른방법을 어떻게 해야할지.....
> [8주차] JAVA : 타겟 넘버

- programmers/hellozo0/dfs-bfs/게임_맵_최단거리.java
최단거리로 목적지에 도착하는 길이? 카운팅
미로 유형의 문제...-> dx dy로 위아래 다 검색하며 갈 수 있는 방향으로 탐색~!
dfs/bfs
미로 유형의 문제는 항상 bfs로 풀었던거 같다 특히나 dx dy 관련 된거는..!!! 
- 시간복잡도 : O(n+e..?)
> [8주차] JAVA : 게임 맵 최단거리

- programmers/sung-silver/단어변환.java
- 단어변환: https://school.programmers.co.kr/learn/courses/30/lessons/43163
- 가지치기하면서 경우의 수를 다 따져보자
- dfs
- begin으로 들어오는 값을 기준으로 words를 탐색
- 탐색중 만약 단어가 begin과 한글자만 다르다면 그 단어부터 visited를 사용하여 탐색 유무를 확인하며 경우의 수를 만들어 나간다
- visited가 false이면서 한 글자 차이인 글자인지 확인하며 idx(글자가 변하는 갯수)를 갱신 
- 시간복잡도 : O(n!)
- 공간복잡도 : O(n)
- 시간복잡도가 n!이 되는게 맞나..?!
> [9주차] JAVA: 단어변환

- programmers/Hong0329/dfs-bfs/week9-1.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/43163
* dfs를 사용하여 바뀔 수 있는 단어들을 다 가본다.
* 주어진 words에 target이 없다면 dfs를 돌리기 전에 0을 출력한다.
* dfs
* 시작 단어로 부터 바뀔 수 있는 단어로 바뀌어 본다.
* 바뀐 후에 또 바뀔 수 있는 단어들을 찾아보며 바뀌어본다. 
* 원하는 단어가 된다면 그때의 횟수를 answer에 저장해놓는다.
- 시간복잡도 : 음 조금 더 고민해볼게요 ㅠ
- 공간복잡도 : O(n)
* 없습니다.
> [9주차] C++ : 단어 변환

- programmers/Hong0329/dfs-bfs/week9-2.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/43164
* dfs로 이어진 공항들을 가본다.
* dfs
* dfs로 시작 지점부터 이어진 공항들을 다 가본다.
* 만약 끊겼고, 이때까지 돌아본 공항들이 전체 공항의 개수가 아니라면 방문여부를 되돌리며 이전 단계로 돌아간다.
* 알파벳 순으로 정렬하는 것은 주어진 티켓들을 sort하고 dfs를 돌린다면 자동으로 처리된다.
- 공간복잡도 : O(n)
* 없습니다.
> [9주차] C++ : 여행경로

- programmers/hellozo0/dfs-bfs/단어변환.java
begin 단어에서 한단어만 변경해서 words에 있는 단어로 변경할 수 있다. 그리고 최종적으로는 target이 되는것!
dfs를 잘 쓰고 bfs로 넘어가고 싶어서 dfs로 풀어봤다.
그리고 뭔가 재귀 느낌이 강해서 dfs로 풀어봤느데 words의 단어가 얼마 없어서 아마 bfs가 더 좋았을 지도
dfs/bfs
주석으로 단계를 풀어놨다.
- 시간복잡도 : O(V+E) - 인데 노드 개수N, 간선 개수는 조건에 따라 다르다.. 따라서... 지금 보니 왠지 DFS로 계산 불가 한거 보니까 BFS로 ㅍ루어야했나..?
- 공간복잡도 : O(N) - visited 사용
음엄,,, BFS 로고 풀어보면 좋을거 같다
> [9주차] JAVA : 단어변환

- programmers/hellozo0/dfs-bfs/여행경로.java
ICN 에서 ticket에 있는 노선에 따라 이동하며... 여행 경로 짜기
이전 문제랑 비슷하게 재귀 느낌이 강해서 DFS로..!
DFS/BFS
주석 참고 
- 시간복잡도 : O(N) - ticket에 다 새로운 이름이 있따고 치면 V = N, E는 tickets의 length 만큼 따라서 O(2N)
- 공간복잡도 :O(N)
그 list에 이름 + " " + 다음꺼 이런식으로 저장해여할 생각을 못했었다..또르르륵
> [9주차] JAVA : 여행경로

- programmers/sung-silver/dfs-bfs/퍼즐_조각_채우기.java
- 퍼즐 조각 채우기: https://school.programmers.co.kr/learn/courses/30/lessons/84021
- 감을 잡지 못했,,음
- bfs
- 퍼즐빈칸, 조각 좌표 구하기 : BFS - queue
- 좌표 90도 회전 -> x, y = y, -x
- 회전후 왼쪽위 좌표 기준으로 정렬 and 왼쪽위 좌표를 0, 0으로 계산
- 시간복잡도 : O(N^3)
- 이중 반복문 내에서는 각 요소의 크기를 비교하기 위해 리스트의 크기만큼 반복 (N*N*N) 
- https://tmdrl5779.tistory.com/206 여기 코드가 제일 직관적으로 이해하기 쉬웠음
- 개인적으로 dfs는 감을 잘 잡았는데 bfs는 약간 매엥 한 느낌이랄까,.
> [9주차] JAVA: 퍼즐 조각 채우기

- programmers/hellozo0/dfs-bfs/아이템_줍기.java
https://school.programmers.co.kr/learn/courses/30/lessons/87694
일단 좌표 관련된 탐색이다? -> BFS다   말고는 어떻게 풀지 감이 안 잡혔다 ㅠㅠ 
시작위치에서 종료위치로 가는 것을 count
DFS / BFS
좌표 문제는 얼 추 형태가 비슷한데 
구글링 해보니 X2, 하는 이유를 알아야하는데 그 생각을 못했다. 그리고 어떻게 코드를 짜야하는지 파악을 못함 ㅠㅡㅠ 
BFS 문제 분석 -> 수도코드 작성부터 연습 해야할 듯하다... 
- 시간복잡도 :
- 공간복잡도 : O(N^2) 
몰라서 아쉬운것도 업어요 
폭룡적인 그림과 보기만해도 풀기 싫은 문제들....
> [9주차] JAVA : 아이템 줍기

- programmers/unanchoi/bfsdfs/단어변환.py
- programmers/unanchoi/bfsdfs/여행경로.py
https://school.programmers.co.kr/learn/courses/30/lessons/43164
- 항공편을 graph로 담아서 dfs로 해결
- 시간복잡도 :
- defaultdict를 생각하지 못했다 ..
> [9주차] PYTHON: 여행 경로

- programmers/unanchoi/bfsdfs/아이템줍기.py
https://school.programmers.co.kr/learn/courses/30/lessons/87694
BFS & DFS
- 시간복잡도 :
- 공간복잡도 :
프로그래머스 풀이를 참고함.. 너무 어려웠다.
> [9주차] PYTHON: 아이탬 줍기

- programmers/Hong0329/dfs-bfs/week9-3.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/87694
* 겹치는 사각형의 영역을 처리하는 것이 중요하겠다.
* dfs
* 이건 구글링을 통해서 풀었어요... 어떻게 2배로 늘릴 생각을 했지....
- 시간복잡도 : O(n)
- 공간복잡도 : O(10000)
* 구글링 없이는 아이디어를 못떠올렸어요...
> [9주차] C++ : 아이템 줍기

- programmers/hellozo0/dfs-bfs/퍼즐_조각_채우기.java
간단하게 말하면 테이블 위에 놓인 퍼즐 조각을 게임 보드의 빈칸에 채우기 ( 다만 조건에 맞게)
음 일단 재귀로 풀기에는 너무 Big 하다 그래서 BFS로 풀어야한다는 생각을 갖고 시작했다.
DFS/BFS
어떻게 풀건지 생각을 못함 -> 구글링 코드도 겨우 이해. 이해는 했지만 다시 해보라고 하면 못할듯
- 시간복잡도 :
그냥 틀리겠다. 하지만 아 이거 대강 이렇게 이렇게 이러쿵 저러쿵 ~ 인데 만 알아도 면접가서 말하수는 있을 듯하여 
담주에 한번 또 보겠다
> [9주차] JAVA : 퍼즐 조각 채우기

- programmers/Hong0329/dfs-bfs/week9-4.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/84021
* 분석 실패...........................ㅠㅠㅠ
- 시간복잡도 :
- 공간복잡도 :
* 어렵네요.....
> [9주차] C++ : 퍼즐 조각 채우기

- programmers/unanchoi/binarysearch/징검다리.py
- 이진 탐색으로 바위 사이의 최소 거리를 찾고, 거리가 작은 바위들을 순회하면서 제거함.
- 시간복잡도 : O(NLogN)
- 공간복잡도 :  O(N)
- 어려워서 풀이를 참고했습니다..
> [10주차] PYTHON: 징검다리

- programmers/unanchoi/binarysearch/입국심사.py
https://school.programmers.co.kr/learn/courses/30/lessons/43238
- 이분탐색
- n을 기준으로 심사할 사람의 수를 계산해서, 사람의 수와 비교하여 값이 크면 mid를 줄이고, 값이 작으면 mid가 작게 업데이트 한다.
- 시간복잡도 : O(LogN)
- 공간복잡도 : O(N)
- 이분탐색을 오랜만에 해서.. 많이 헤맸다 ..
> [10주차] PYTHON : 입국심사

- programmers/Hong0329/binary_search/week10-1.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/43238
* 최대 소요 시간을 정할 수 있기 때문에 그것을 가장 끝으로 잡고 이분 탐색을 돌린다.
* 이분 탐색
* 최대 소요 시간을 정할 수 있기 때문에 그것을 가장 끝으로 잡고 이분 탐색을 돌린다.
* 점화식으로는 해당 시간을 심사관 소요 시간으로 나눠서 해당 시간에 최대로 심사할 수 있는 명 수를 구한다.
- 시간복잡도 : O(log2N)
- 공간복잡도 : O(n)
* 없습니다.
> [10주차] C++ : 입국심사

- programmers/hellozo0/binary_search/징검다리.java
https://school.programmers.co.kr/learn/courses/30/lessons/43236
아 생각하느라 시간이 좀 오래 걸렸다 뭔가 간격을 좁혀 나가며 푼다는 ㅡ느낌이 들어서 이진탐색인게 적합했따.
이진탐색
- 시간복잡도 : 아까랑 같이 O(nlogn) 정렬이 시간 더 오래 걸려서
- 공간복잡도 : O(logn)
음 그 `if(distance - prev < mid && remove <= n) remove++;` 이 부분 조건이 잘못되어서 계속 틀렸는데 AI 선생님이 갑자기 생겨 나서 이래라 저래라 해주셔서 다시 생각해봤다.. 어디가 틀린지 집어줘서 도움이 된거 같기두... 프ㅜ로그래머스도 발전하는구나..
> [10주차] JAVA : 징검다리

- programmers/sung-silver/binary/입국심사.java
- 입국심사: https://school.programmers.co.kr/learn/courses/30/lessons/43238
- 최대 소요 시간을 정하여 이분탐색 돌리기
- 이분 탐색
- 해당 시간을 심사관 소요 시간으로 나눠서 해당 시간에 최대로 심사할 수 있는 명 수를 구한다.
- 시간복잡도 : O(log2N)
- 공간복잡도 : O(n)
- 왜.. 제출을 안했을까요?
> [10주차] JAVA: 입국심사

- programmers/sung-silver/binary/징검다리.java
- 징검다리: https://school.programmers.co.kr/learn/courses/30/lessons/43236
- 간격 거리를 기준으로 이분탐색을 돌린다
- 이분탐색
- 생길 수 있는 간격을 기준으로 이분 탐색을 돌린다.
- 공간복잡도 : O(n)
- 왜 안..냈을까요 ㅎㅎ
> [10주차] JAVA: 징검다리

- programmers/sung-silver/graph/가장_먼_노드.java
- 가장 먼 노드: https://school.programmers.co.kr/learn/courses/30/lessons/49189
- bfs라는 느낌이 들었다
- bfs
- maxDepth == depth : answer에 1을 더해준다.
- maxDepth < depth : 현재 노드가 가장 먼 노드이다. maxDepth를 depth로 갱신하고 answer를 1로 초기화한다.
- 시간복잡도 : O(n+m)
- 공간복잡도 : O(n+m)
- bfs가 맞는 것 같은데 그래프 유형이라서 연관은 있을 수도 있는데 뭔가 확신을 가지고 풀이를 못했었던 것 같음 왜지..? 하하
- 시간, 공간 복잡도가 이해가 안될 때 GPT한테 설명을 부탁하는데 n+m 이런 식을 머리로 바로바로 도출이 잘 안되는 것 같음.. 간선이 중요하다
> [11주차] JAVA: 가장 먼 노드

- programmers/sung-silver/graph/순위.java
- 순위: https://school.programmers.co.kr/learn/courses/30/lessons/49191
- 프로이드 와샬 알고리즘을 이용하자 (이 아이디어도 구글링을 통해 알게 되었다)
- 그래프
- 프로이드 와샬 알고리즘을 이용한다
- n명의 선수가 있을 때 나를 제외한 n-1명과의 경기 결과를 알면 나의 순위를 알 수 있다.
- 위의 예제에서 보았듯이 5명의 선수 중 4위 선수에게 패배했을 때 나의 순위는 5위가 된다. n-1명과 경기를 안 펼쳐도 내 순위를 알 수 있다.
- 예시로 b선수가 a선수를 이겼다. a선수는 c선수를 이겼다. 그렇다면 b선수와 c선수는 경기를 치루지 않아도 선수가 c선수보다 순위가 높다.
- 즉, b > a && a > c 이면 b > c이다.
- 이를 이용하여 플로이드 와샬 알고리즘을 수행한 후 한 선수에 대해 n-1 선수의 승/패 정보를 알면 순위를 알 수 있다.
- 시간복잡도 : O(N^3)
- 특정 알고리즘을 알면 더 쉬운 문제일 수 있는 것 같은데 이에 관련된 지식이 좀 부족한 기분..? 느낌?? 그래서 다음 알고리즘 스터디의 방향성에 대해 좀 더 고민하게 된 문제였던 것 같음!!
> [11주차] JAVA: 순위

- programmers/sung-silver/graph/방의_개수.java
- 방의 개수: https://programmers.co.kr/learn/courses/30/lessons/49190
- ㅋㅋㅋ 어려웠다..코드를 많이 참고함
- 그래프
- 참고한 풀이의 해결 방안은 다음과 같다
- 고려 사항
1. 방문했던 정점(node)을 재방문하는 경우, 방이 생성된다.
2. 기존에 통과한 간선(edge)을 재통과하는 경우에는 정점을 재방문해도 방이 생성되지 않는다.
3. 각 정점(node)의 단위가 작아 간선(edge)끼리의 교차가 발생할 수 있다. 이를 위해 단위를 스케일업 해준다.
- 생각해야 하는 부분
1. Java의 경우, 좌표에 대한 객체를 만들어야 좌표간 비교가 가능해진다.
- hashCode 함수와 equals 함수를 통해 값 비교
- 만약 위 두 함수가 없으면 주소값 비교
2. 방문했던 점은 해쉬맵의 키값에 넣고, 그 점과 연결되었던 점들은 리스트화해서 추가한다.
3. 방문할 점의 경우 기존의 점과 연결되어 있는지를 리스트 내에서 확인한 후 카운트를 올려야 한다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 보고 이해했던 것.. 그래서 나중에 다시 풀려고 프로그래머스 인증자체를 하지 않았다
> [11주차] JAVA: 방의 개수

- programmers/unanchoi/방의개수.py
https://school.programmers.co.kr/learn/courses/30/lessons/49190
- 그래프
x,y 변화량을 dx, dy로 만들고 이동하면서, 위치를 계산하고 visited 여부를 판단하여, answer를 계산함.
- 시간복잡도 : O(N)
- 어려워서 풀이 참고했습니다 ...!
> [11주차] PYTHON: 방의개수.py

- programmers/unanchoi/graph/순위.py
https://school.programmers.co.kr/learn/courses/30/lessons/49191
- 그래프
플로이드 워셜 알고리즘 ..?
- 시간복잡도 : O(N)
- 어렵네요 ..
> [11주차] PYTHON : 순위.py

- programmers/unanchoi/graph/가장먼노드.py
https://school.programmers.co.kr/learn/courses/30/lessons/49189
그래프
BFS로 풀이
- 시간복잡도 : O(N)
- 어렵네요 ..
> [11주차] PYTHON 가장먼노드.py

- programmers/hellozo0/graph/가장_먼_노드.java
노드의 거리가 가장 먼것의 개수
그래프, 그리고 엣지 검색이라 bfs, 엣지 리스트로 최적화
그래프,
주석 아무지게 달아둠
- 시간복잡도 : O(V+E) ==> O(n + edge.length)
- 공간복잡도 : O(edge.length)
읎슴
> [11주차] JAVA : 가장 먼 노드

- programmers/hellozo0/graph/순위.java
순위가 확정된 선수들의 수 구하기
bfs,dfs 같은걸 사용하는게 아니라....몰라서 구글링을 헀따. -> 플로이드 와샬(인접행렬 사용)
플로이드 와샬(인접행렬 사용)
n-1의 순서를 알면 내 순서가 정해진다는 원리이다.
- 시간복잡도 : O(n^3)
와샬,.........ㅠㅡㅠ.. 무엇보다 최단거리? 구할떄 쓰는 알고리즘인데
n-1의 순서를 알면 내 순서가 정해진다 --> 이 아이디어를 떠오리기가 어려웠고 어떻게 바로 와샬쓸지 생각하지?
그래프문제 좀 풀어봐야겠따 종류도 넘 많다
> [11주차] JAVA : 순위

- programmers/Hong0329/graph/week11-1.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/49189
* BFS를 통해서 1번 노드로 부터 다른 노드들까지의 거리를 구한다.
* 그래프
* BFS를 통해서 1번 노드로 부터 다른 노드들까지의 거리를 구한다.
* max_element를 통해서 가장 먼 노드까지의 거리를 구한 후에 해당 거리만큼 떨어진 노드들의 개수를 구한다.
- 시간복잡도 : O(n + edge.size())
- 공간복잡도 : O(n+ edge.size())
* 없습니다.
> [11주차] C++ : 가장 먼 노드

- programmers/hellozo0/graph/방의_개수.java
노드를 그려서 방의 개수를 구하기 
이거 저번에 bfs 였나 비슷한 그림 그리기 문제가 있었던거 같은데..
일단은 direction 사용 하는거 파악
노드 클래스 사용해야하는거 까지는 파악..
근데 hasCode, Equals, 그 방이 만들어 지는 포인트 파악 -> 요 부분들을.............몰랐다 
그래프
주석으로 적어둠! 로직 자체는 어렵지 않았음 
- 시간복잡도 : O(n)인데 근데 문제가 객체 에서 값 비교 하는게 있어서 그러묜 또... ㅇㅅㅇ... 모르게따
- 공간복잡도 : 음 객체를 써서 O(n)? 인가..?
요런 객체의 함수 같은것들을 어떻게 써야할란지
> [11주차] JAVA : 방의 개수

- programmers/Hong0329/graph/week11-2.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/49191
* 플로이드 와샬
* 플로이드 와샬
* 플로이드 와샬로 선수들간의 승리여부를 부여한다.
* 선수들에 대해서 다른 선수들과의 승리여부가 모두 나와있다면 그 선수의 순위를 지정할 수 있다.
- 시간복잡도 : O(n^3)
* 플로이드 와샬이 너무 오랜만이었다.
> [11주차] C++ : 순위

- programmers/Hong0329/graph/week11-3.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/49190
못했어요...ㅠ
- 시간복잡도 :
- 공간복잡도 :
좀 더 공부해보겠습니다.
> [11주차] C++ : 방의 개수

- programmers/algorithm/level2/unanchoi/귤고르기.kt
https://school.programmers.co.kr/learn/courses/30/lessons/138476
- 정렬
-  Map에 귤의 개수를 저장하고 정렬을 사용하여 귤의 최소개수를 카운트
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 문제 이해가 어려웠다.
> [12주차] KOTLIN: 귤 고르기

- programmers/algorithm/level2/Hong0329/week12-algo3.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12941?language=cpp
* A배열의 최소와 B배열의 최대를 곱해야 가장 작은 합의 값을 구할 수 있다.
* 정렬
* A배열의 최소와 B배열의 최대를 곱해야 가장 작은 합의 값을 구할 수 있다.
- 시간복잡도 :O(nlogn)
- 공간복잡도 : O(n)
없습니다.
> [12주차] C++ : 최솟값 만들기

- programmers/algorithm/level2/Hong0329/올바른_괄호.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12909
* key라는 값을 기준으로 (는 ++, )는 -- 하여 최후의 값을 확인한다.
* 구현?
* key라는 값을 기준으로 (는 ++, )는 -- 하여 최후의 값을 확인한다.
* 중간에 key가 음수가 된다면 잘못된 괄호가 된다.
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
없습니다.
> [12주차] C++ : 올바른 괄호

- programmers/algorithm/level2/Hong0329/최대값과_최솟값.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12939
* 문자열 자르고 형변환 후 비교
* 구현?
* 공백을 기준으로 문자열을 자르고 자른 문자들을 정수형으로 형변환한다.
* 변환한 정수들을 벡터에 넣어 정렬한다.
- 공간복잡도 : O(n)
없습니다.
> [12주차] C++ : 최댓값과 최솟값

- programmers/algorithm/level2/sung-silver/최솟값_만들기.java
- 최솟값 만들기: https://school.programmers.co.kr/learn/courses/30/lessons/12941
- 어떤 배열의 최솟값과 또 다른 배열의 최댓값을 곱하면 그 합이 최소가 된다
- 정렬
- 두 배열을 모두 오름차순으로 정렬하고, A 배열의 최소값과 B 배열의 최대값을 곱하여 답을 구한다
- 공간복잡도 : O(n)
> [12주차] JAVA: 최솟값 만들기

- programmers/algorithm/level2/sung-silver/올바른_괄호.java
- 올바른 괄호: https://school.programmers.co.kr/learn/courses/30/lessons/12909
- 괄호를 짝지으러면 어떤걸 사용할까... -> 스택
- 스택
- ( 이면 스택에 넣고 )이면 짝지을 (를 스택에서 꺼내어 짝을 만들어준다
- )이 등장했을 때 스택에 짝지을 (가 없으면 올바른 괄호가 아니다
- 모든 문자열에서 괄호를 짝짓고나서 스택에 (가 남아있으면 올바른 괄호가 아니다
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
> [12주차] JAVA: 올바른 괄호

- programmers/algorithm/level2/sung-silver/최대값과_최솟값.java
- 최대값과 최솟값: https://school.programmers.co.kr/learn/courses/30/lessons/12939
- 문자열을 한글자씩 비교하자
- 문자열?
- 하나씩 비교하여 최대 최소를 각각 구한다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 저도 그냥 프로그래머스에서만 푸는 걸 연습중인데...StringTokenizer와 관련된 함수가 추천되어 뜨지 않으니 자연스레 구글링을 하게 되네요 핫..
> [12주차] JAVA: 최댓값과 최솟값

- programmers/sql/sung-silver/있었는데요_없었습니다.sql
- 있었는데요 없었습니다: https://school.programmers.co.kr/learn/courses/30/lessons/59043
- animal_ins와 animal_outs의 datetime 차이 이용
- join, where, order by
- 예전에는 datediff로 풀었던 것 같은데 틀려서 같은 날짜의 시간이 차이나는 부분이 있다고 생각해 timestampdiff로 풀이
- timestampdiff는 인자가 3개 필요한데 앞에는 기준(MINUTE, SECOND...) 2번째 인자를 A, 3번째 인자를 B라고 했을 때 A-B의 결과가 아니라 B-A의 결과를 반환..그래서 timestampdiff를 사용하고도 한 번 틀렸었다
> [12주차] SQL: 있었는데요 없었습니다

- programmers/sql/sung-silver/카테고리_별_도서_판매량_집계하기.sql
- 카테고리 별 도서 판매량 집계하기: https://school.programmers.co.kr/learn/courses/30/lessons/144855
- 두개 조인해서 group by로 카테고리별 판매량을 구하고 2022.01 판매량인지 검사
- join, group by
- 두개 조인해서 group by로 카테고리별 판매량을 구하고 2022.01 판매량인지 검사
X
> [12주차] SQL: 카테고리 별 도서 판매량 집계하기

- programmers/hellozo0/week12/최솟값_만들기.java
정렬먼저 해야겠다고 생각했음 ! 
정렬 후 ...ing
일단 정렬 한 후에 조건에 맞게 반복문 & 식 세움
- 시간복잡도 : O(nlogn) -> sort로 인해...
- 공간복잡도 : O(n)
ㄴㄴ
> [12주차] JAVA : 최솟값 만들기

- programmers/hellozo0/week12/올바른_괄호.java
이전에 풀었던 스택 문제! 이므로,,, 아래의 내용들은 스그하게 패스할께여
- 시간복잡도 :
- 공간복잡도 :
> [12주차] JAVA : 올바른 괄호

- programmers/hellozo0/week12/최댓값과_최솟값.java
max, min 구하기
max, min 구하기
메소드 사용
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
없음음
> [12주차] JAVA : 최댓값과 최솟값

- programmers/algorithm/level2/hellozo0/week13/dummy.java
- programmers/sql/hellozo0/date/조건별로_분류하여_주문상태_출력하기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/131113
DATE
CASE WHEN THEN 
출고완료 어떻게 해야할지 몰라 고민했다... 안풀다가 sql 푸니까 진짜 감떨어졌따 떼굴루ㅜ룰
처음에는 WHERE에 써야하나 했는데 아니였음
> [13주차] SQL : 조건별로 분류하여 주문상태 출력하기

- programmers/algorithm/level2/hellozo0/week13/JadenCase_문자열_만들기.java
- programmers/algorithm/level2/hellozo0/week13/dummy.java
문자열 활용
공백다음에는 단어의 시작임을 알고 시작하면 된다
문자열
flag로 단어의 시작이 되는 부분을 체크한다.
처음, 공백 이후의 단어는 대문자다 -> 이부분을 if/else로 작성
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
Nothing
> [13주차] JAVA : JadenCase 문자열 만들기

- programmers/sql/sung-silver/오랜_기간_보호한_동물_1.sql
- 오랜 기간 보호한 동물: https://school.programmers.co.kr/learn/courses/30/lessons/59044
- 어떤 테이블에는 정보가 있고, 어떤 테이블에는 없다? -> LEFT JOIN
- join
- left join 사용하여 join되는 컬럼이 없어 null로 처리되는 값 찾기
> [13주차] SQL: 오랜 기간 보호한 동물(1)

- programmers/sql/sung-silver/조건별로_분류하여_주문상태_출력하기.sql
- 조건별로 분류하여 주문상태 출력하기: https://school.programmers.co.kr/learn/courses/30/lessons/131113
- 날짜, 조건문
- 조건문
- 시간 차 이용하기
- case when ~ ELSE END
- 조건문 뒤에 END 붙이는거 까먹음 ㅎ
> [13주차] SQL: 조건별로 분류하여 주문상태 출력하기

- programmers/algorithm/level2/sung-silver/JadenCase_문자열_만들기.java
- JadenCase 문자열 만들기: https://school.programmers.co.kr/learn/courses/30/lessons/12951
- 띄어쓰기 뒤에 오는 단어를 대문자로 만들자
- 문자열
- 앞에 공백이 오는지 확인 후 대문자로 변환
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
> [13주차] JAVA: JadenCase 문자열 만들기

- programmers/algorithm/level2/sung-silver/이진_변환_반복하기.java
- 이진 변환 반복하기: https://school.programmers.co.kr/learn/courses/30/lessons/70129
- 주어진 조건 순서대로 구현하면 되겠다
- 문자열
- 0을 없앤다
- 없앤 0을 센다
- 0을 없앤 문자열의 길이를 이진법으로 표현한다 -> `Integer.toBinaryString()` 사용
- 문자열이 1이 될 때까지 반복
- 시간복잡도 : O(NlogN)
- 공간복잡도 : O(N)
- `Integer.toBinaryString()`를 몰라서 찾아봤다!
> [13주차] JAVA: 이진 변환 반복하기

- programmers/algorithm/level2/sung-silver/숫자의_표현.java
- 숫자의 표현: https://school.programmers.co.kr/learn/courses/30/lessons/12924
- 연속된 자연수의 덧셈
- 이중 반복문
- 각 시작 숫자로부터 연속되는 값을 더하여 주어진 숫자가 되는지 확인한다
- 숫자가 같으면 answer를 증가하고, 연속된 수를 더하다가 숫자가 같아지는 시점 없이 더 커지게 되면 내부 반복문을 빠져나온다
- 공간복잡도 : O(N)
> [13주차] JAVA: 숫자의 표현

- programmers/algorithm/level2/hellozo0/week13/dummy.java
- programmers/algorithm/level2/hellozo0/week13/숫자의_표현.java
연속합 수 구하기
대표적인 슬라이딩 윈도우 문제
대표적인 슬라이딩 윈도우 문제
index 조절로 n일 경우 count++
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
놉 , 마지막에 end 인덱스 때문에 디버깅 했는데 딱히 좋은 조건문 안 떠올라서 ...ㅎㅎ...
> [13주차] JAVA  : 숫자의 표현

- programmers/algorithm/level2/hellozo0/week13/dummy.java
- programmers/algorithm/level2/hellozo0/week13/이진_변환_반복하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/70129?language=java
조건 잘 생각해서.... 단순 구현..?
단순 구현
Integer.toBinaryString 메소드만 알고 있으면 10진수 -> 2진수 가능
toBinaryString을 몰랐음
> [13주차] JAVA : 이진 변환 반복하기

- programmers/algorithm/level2/Hong0329/JasenCase문자열 만들기.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12951
* 문자열을 처음부터 보면서 조건에 맞으면 대문자 또는 소문자로 만든다.
* toupper tolower?
* 문자열을 처음부터 보면서 조건에 맞으면 대문자 또는 소문자로 만든다.
- 시간복잡도 :O(n)
- 공간복잡도 : O(n)
* 없습니다.
> [13주차] C++ : JadenCase문자열 만들기

- programmers/algorithm/level2/Hong0329/이진 변환 반복하기.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/70129
* 문제에서 나온 과정을 조건에 걸릴 때까지 돌린다.
* 문자열
* 0을 없애고, 그 길이 만큼 다시 2진법을 만든다. 1이 될때까지 반복한다.
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
* 없습니다.
> [13주차] C++ : 이진 변환 반복하기

- programmers/algorithm/level2/Hong0329/숫자의 표현.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12924
* n보다 작은 숫자들에 대해서 연속된 숫자들을 더해본다. 
* 구현?
* n보다 작은 숫자들에 대해서 그 숫자를 시작으로 연속된 숫자들을 더해본다.
* 이때 조건에 맞으면 answer++
- 공간복잡도 : O(n)
* 없습니다.
> [13주차] C++ : 숫자의 표현

- programmers/algorithm/level2/hellozo0/week14/다음_큰_숫자.java
노가다로 숫자 증가 시키면서 2진수화 해서 1의 개수 구하기
문자열
1. 비교할 기준을 주어진 숫자 n 보다 +1인 숫자를 비교한다. 해당 숫자들을 toBinaeyString 해서 1의 개수를 새는 함수를 따로 만들어서
2. 같을 경우가 나올 때 까지 반복분 수행, 아닌 경우에는 숫자 +1 해서 비교 
- 시간복잡도 : O(n) ...? 아 애매하다 
- 공간복잡도 : O(n)
없음
> [14주차] JAVA : 다음 큰 숫자

- programmers/algorithm/level2/hellozo0/week14/피보나치_수.java
https://school.programmers.co.kr/learn/courses/30/lessons/12945
음 재귀 말고 반복문으로 배열에 bottom up
DP? 
반복문으로 배열에 bottom up 값 누적하기!
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
없다
> [14주차] JAVA : 피보나치 수

- programmers/algorithm/level2/hellozo0/week14/짝지어_제거하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/12973
처음에는 그냥 노가다로 생각했는데, 이런 문제 코테에 나온적 있어서 생가해보니 스택으로 푸는것
스택
스택에 값을 넣고 peek로 값이 같다면~ pop 한다. 
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
첨에 바로 스택 써야하는것을 떠올리지 못했다.
근데 이런 유형 ? 코테에서 본거 같아서 진짜 빨리 후딱 풀 수 있게 연습해야겠다는 생각
> [14주차] JAVA : 짝지어 제거하기

- programmers/sql/sung-silver/오랜_기간_보호한_동물_2.sql
- 오랜 기간 보호한 동물: https://school.programmers.co.kr/learn/courses/30/lessons/59411
- inner join으로 풀자
- inner join, order by, limit
- 정렬 기준으로 퇴소 날짜와 입소 날짜를 빼서 정렬
> [14주차] SQL: 오랜 기간 보호한 동물(2)

- programmers/sql/sung-silver/보호서에서_중성화한_동물.sql
- 보호소에서 중성화한 동물: https://school.programmers.co.kr/learn/courses/30/lessons/59045
- inner join해서 sex_upon_(in/out)come 비교하기
- inner join
- like
- 조인해서 들어올 때 상태는 중성화 X, 나갈때 상태는 중성화 O인 동물을 찾는다
> [14주차] SQL: 보호소에서 중성화한 동물

- programmers/algorithm/level2/sung-silver/다음_큰_숫자.java
- 다음 큰 숫자: https://school.programmers.co.kr/learn/courses/30/lessons/12911
- Integer.toBinaryString을 사용해야겠다..
- 단순 구현?
- 일단 인자로 받은 n에 대해서 이진법으로 바꾸고 그 이진법으로 바꾼 문자열에서 1의 개수를 센다
- 인자로 받은 n보다 1큰 숫자부터 하나씩 증가하여 똑같이 그 숫자들을 이진법으로 바꿔서 1의 개수를 센 값과 내가 미리 세둔 n의 이진수로 바꾸었을 때의 1의 개수가 같아지는 시점에 반복문을 빠져나오고 그 숫자를 반환한다
- 공간복잡도 : O(N)
- Integer.toBinaryString()은 좋은 친구다..
> [14주차] JAVA: 다음 큰 숫자

- programmers/algorithm/level2/sung-silver/피보나치_수.java
- 피보나치 수: https://school.programmers.co.kr/learn/courses/30/lessons/12945
- 순차 탐색으로 각 함수의 결과를 저장하자
- 수학?
- 앞의 두 원소를 더하여 i번째 수를 fibo 배열의 i인덱스에 저장한다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 수의 범위 오버플로우를 고려하지 못함
- (a+b)%n = (a%n + b%n)%n -> 나머지를 더해서 나눠도 나머지가 같다는 것을 알아야함
> [14주차] JAVA: 피보나치 수

- programmers/algorithm/level2/sung-silver/짝지어_제거하기.java
- 짝지어 제거하기: https://school.programmers.co.kr/learn/courses/30/lessons/12973
- 중복되는 부분을 제거한후에 그 앞뒤를 다시 이어 붙인다..?
- 스택
- 처음 풀이: 중복되는 문자열을 앞에서부터 제거 -> 남은 문자열을 다시 검사
- 함수로 만들라고 했는데 반환되는 문자열이 무조건 ""이 되는게 아니여서 조건이 애매해짐
- 포기
- 두번째 풀이
- 스택에 넣고 빼고를 하는데에 넣기 전 가장 최상단의 원소와 지금 push 하려는 원소를 비교
- 한번의 탐색으로 중복을 모두 제거 가능
- 이게 정답이었삼
- 스택에서 남은 원소를 모두 꺼내 거꾸로 문자열을 만들면 중복이 제거된 결과의 문자열 -> 이 길이가 0이면 모두제거한 것 아니면 0을 반환함  
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 처음부터 스택을 못 떠올린거?!
> [14주차] JAVA: 짝지어 제거하기

- programmers/algorithm/level2/Hong0329/다음 큰 숫자.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12911
* 받은 수부터 1씩 더해가면서 이진수로 표현했을 때 1의 개수가 같은 값을 찾는다.
* 구현
* 받은 수부터 1씩 더해가면서 이진수로 표현했을 때 1의 개수가 같은 값을 찾는다.
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
없습니다.
> [14주차] C++ : 다음 큰 숫자

- programmers/algorithm/level2/Hong0329/피보나치 수.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12945
* DP
* DP
* 앞의 두개의 값을 더해서 현재의 값을 채운다.
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
* 없습니다.
> [14주차] C++ : 피보나치 수

- programmers/algorithm/level2/Hong0329/짝지어 제거하기.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12973
* 자료구조 사용
* 스택
* 현재 값이랑 스택의 top이랑 비교하여 같으면 스택을 pop, 다르면 현재 값을 스택에 넣는다. 
* 마지막에 스택이 비어있으면 모두 제거한 것, 아니면 0반환
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
* 시간복잡도 계산으로 단순 구현은 안될 것이란걸 계산했지만 자료구조로 해결할 생각은 좀 걸렸다.
> [14주차] C++ : 짝지어 제거하기

- programmers/algorithm/level2/unanchoi/피보나치수.kt
https://school.programmers.co.kr/learn/courses/30/lessons/12945
- DP
- DP 대표 유형 문제
- 점화식을 생각하고, 점화식에 맞춰서 코드 작성
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
> [14주차]  Kotlin: 피보나치수

- programmers/unanchoi/lv2/다음큰숫자.java
https://school.programmers.co.kr/learn/courses/30/lessons/12911
- 시간복잡도 :
- 공간복잡도 :
> [14주차] Java: 다음큰숫자.java

- programmers/sql/unanchoi/조건별로분류하여주문상태출력하기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/131113
조회시에 CASE 분류
- CASE라는 키워드를 사용.
- 시간복잡도 :
- 공간복잡도 :
- 처음 보는 문법
> [14주차] SQL:  조건별로 분류하여 주문상태 출력하기

- programmers/algorithm/level2/hellozo0/week15/카펫.java
https://school.programmers.co.kr/learn/courses/30/lessons/42842
그리디?
구글링을 해온 방법이다. 이전에 푼 방법이 너무 노가다? 였어서 왠지 좋은 방법이 있을 듯 하여 찾아봄 
``` code
예를 들어, brown = 10,  yellow = 2 이라고 가정할 때, 12의 약수를 구한다 (1, 12) , (2, 6) , (3, 4) , (4, 3) , (6, 2) , (12, 1)
이렇게 구한 경우의 수 중에서 정답을 골라야 한다.
일단 가로의 길이가 세로보다 길거나 같다고 제한사항에 있으므로 경우의 수가 (4, 3) , (6, 2) , (12, 1)로 줄어든다.
또한, 가운데에 노란색 격자가 위치하기 위해선 가로, 세로 길이가 모두 3 이상이여야 하므로 (6, 2) , (12, 1)는 걸러진다.
마지막으로 해당 카펫이 입력으로 주어진 yellow의 개수만큼 노란색 격자가 가운데에 위치할 수 있는지 구해야한다.
(가로 - 2) * (세로 - 2 ) = yellow의 개수이므로 (4 - 2) * (3 - 1) = 2이다. 그러므로 정답.
```
- 공간복잡도 : O(n)
> [15주차] JAVA : 카펫

- programmers/algorithm/level2/hellozo0/week15/점프와_순간_이동.java
https://school.programmers.co.kr/learn/courses/30/lessons/12980
약간 이런 장황하게 문제 설명하는 유형...참....싫타.....
음..그리디? 
그 규칙에 맞게 생각해보면, n을 2로 나눴을때 1이면 ++ 하고, 아니면 /2
X
> [15주차] JAVA : 점프와 순간 이동

- programmers/algorithm/level2/sung-silver/카펫.java
- 카펫: https://school.programmers.co.kr/learn/courses/30/lessons/42842
- 브라운개수+옐로우개수 = 넓이
- 구현..? 뭘까
- 넓이 / 증가되는 너비 = 높이 공식을 세워 비교
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- X
> [15주차] JAVA: 카펫

- programmers/algorithm/level2/unanchoi/점프와순간이동.java
https://school.programmers.co.kr/learn/courses/30/lessons/12980
홀수 짝수일 때 나눠서 풀이
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
문제가 길어서 이해하는데 오래걸림
> [15주차]  Java : 점프와순간이동.java

- programmers/unanchoi/lv2/카펫.kt
https://school.programmers.co.kr/learn/courses/30/lessons/42842
- 이진탐색
- 시간복잡도 : O(N) 
- 공간복잡도 : O(N)
없음
> [15주차] Kotlin: 카펫.kt

- programmers/algorithm/level2/unanchoi/N개의최소공배수.java
https://school.programmers.co.kr/learn/courses/30/lessons/12953
- 수학
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 풀었던 문제여서 Java로 바꿨어용
> [15주차] Java: N개의최소공배수.java

- programmers/algorithm/level2/Hong0329/카펫.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42842
* 가로 세로와,  갈색 노란색 타일의 개수 사이의 관계를 이용
* 구현
* 가로 세로와,  갈색 노란색 타일의 개수 사이의 관계를 이용
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
X
> [15주차] C++ : 카펫

- programmers/algorithm/level2/Hong0329/N개의 최소공배수.cpp
*https://school.programmers.co.kr/learn/courses/30/lessons/12953
* 유클리드 호제법
* 수학
* 유클리드 호제법 사용
* 백준에서 똑같은 유형을 풀어봤어서 수월했다. 
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
없습니다.
> [15주차] C++ : N개의 최소공배수

- programmers/algorithm/level2/sung-silver/N개의_최소공배수.java
- 시간복잡도 :
- 공간복잡도 :
- 시험...이슈로 다음주에 같이 써둘게요 죄송합니더 ㅜ
> [15주차] JAVA: N개의 최소공배수

- programmers/algorithm/level2/Hong0329/예상 대진표.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12985
* +1한후에 2로 나누면 다음 매칭
* 그리디
* +1한후에 2로 나누면 다음 매칭
- 시간복잡도 : O(logn)
- 공간복잡도 : O(n)
없습니다.
> [16주차] C++ : 예상 대진표

- programmers/algorithm/level2/Hong0329/구명보트.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42885
* 크기 순으로 나열 한 후에 가장 큰 값과 작은 값을 더해서 limit을 넘는지 않넘는지 확인. 넘는다면 이때 무거운 애는 혼자 탈 수 밖에 없음
* 그리디
* 크기 순으로 나열 한 후에 가장 큰 값과 작은 값을 더해서 limit을 넘는지 않넘는지 확인. 넘는다면 이때 무거운 애는 혼자 탈 수 밖에 없음
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
없습니다.
> [16주차] C++ : 구명보트

- programmers/algorithm/level2/Hong0329/멀리 뛰기.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12914
* 1과 2로만 뛸 수 있다면 현재 타일 기준 -1한 것에 올 수 있는 방법과, -2한 것에 올 수 있는 방법을 더하면 구할 수 있다.
* DP
* 1과 2로만 뛸 수 있다면 현재 타일 기준 -1한 것에 올 수 있는 방법과, -2한 것에 올 수 있는 방법을 더하면 구할 수 있다.
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
없습니다.
> [16주차] C++ : 멀리 뛰기

- programmers/sql/sung-silver/식품분류별_가장_비싼_식품의_정보_조회하기.sql
- 식품분류별 가장 비싼 식품의 정보 조회하기: https://school.programmers.co.kr/learn/courses/30/lessons/131116
- group by
- group by, subquery
- 서브쿼리를 쓰고 그 결과 값을 가지고 와야 함
- 처음 시도 코드가 아래였는데 이 코드의 문제점을 빨리 캐치하지 못함
- 비결정적 값인 product_name에 대하여 group by에 명시를 하지 않은 경우 어떤 제품의 이름이 선택될지 결정되지 못하는 문제
```
SELECT CATEGORY, MAX(PRICE) as MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;
```  
- 그래서 category 별로 가장 높은 가격을 서브쿼리로 반환하고 주 쿼리에서 이를 받아 이름까지 출력하는 식으로 풀이해야 정답이 맞는다
> [16주차] SQL: 식품분류별 가장 비싼 식품의 정보 조회하기

- programmers/sql/sung-silver/5월_식품들의_총매출_조회하기.sql
- 5월 식품들의 총매출 조회하기
- 서브 쿼리에서 2022 5월에 생산된 각 id 별 총 생산량을 구하고 주 쿼리에서 이름이랑, 가격이랑 구해서 가격*총생산량으로 total_sales를 구한다
- subquery, group by
- 2번과 같음
X
> [16주차] SQL: 5월 식품들의 총매출 조회하기

- programmers/algorithm/level2/hellozo0/week16/구명보트.java
https://school.programmers.co.kr/learn/courses/30/lessons/42885
어떻게 하면 limit에 가깝게 효율적으로 배를 태울까
그리디
인덱스를 앞과 뒤를 사용해서 더하면 최적의 limit에 맞게 배를 태울 수 있다. 
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
정렬해서 앞에서 묶을 생각을 했는데,,, 그리디 어렵다
> [16주차] JAVA : 구명보트

- programmers/algorithm/level2/hellozo0/week16/예상_대진표.java
https://school.programmers.co.kr/learn/courses/30/lessons/12985?language=java
그리디
음 2로 나눠서 어차피 1,2,3,4 등으로 재 세팅하니까 
2로 나눈 몫과 나머지를 배합해서 값을 구한다
- 시간복잡도 : O(logn) -> 계속 2로 나누니까..? 트리 구조임
- 공간복잡도 : O(n)
아이디어가 안 떠올랐다 ㅠㅠ 반으로 나눌 생각만 했는데
> [16주차] JAVA : 예상 대진표

- programmers/algorithm/level2/hellozo0/week16/멀리뛰기.java
https://school.programmers.co.kr/learn/courses/30/lessons/12914?language=java
아 처음에 보고 그리디인가? 조합? 순열? 피보나치? 크루스칼 삼각형 어쩌구? 대강 스쳐 지나가고 뻘짓함 +DFS까지
DP
DP로 점화식
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
멍청하게 DP로 풀 생각 못해봄... TC 1,2,3,4,5 값 구하는 연습 매일 그냥 어떤 문제든 간에 생각해야겠다
그리고 왜 배열 값 n+2까지 저장해야하지...? 몰겟슴 왜지 뭐지
그리고 주석은 첨에 틀렸을때 생각해본 접근 방법 그럴라면 어차피 조합 할줄 알아야함
> [16주차] JAVA : 멀리 뛰기

- programmers/algorithm/level2/sung-silver/구명보트.java
- 구명보트: https://school.programmers.co.kr/learn/courses/30/lessons/42885
- 오름차순 정렬 후 앞 뒤로 더해서 비교
- 그리디
- 정렬 후 가장 무게가 작은 애랑 가장 큰 애랑 태울 수 있나를 비교
- 공간복잡도 : O(n)
X
> [16주차] JAVA: 구명보트

- programmers/algorithm/level2/sung-silver/멀리뛰기.java
- 멀리 뛰기: https://school.programmers.co.kr/learn/courses/30/lessons/12914
- 앞에 두개를 더하면 다음거의 답..
- dp
- 1을 멀리 뛰는 방법은 1가지
- 2를 멀리 뛰는 방법은 2가지
- 3을 멀리 뛰는 방법은 3가지
- 4를 멀리 뛰는 방법은 5가지
- 5를 멀리 뛰는 방법은 8가지..
- dp[n-2] + dp[n-1] = dp[n]이라는 식을 세울 수 있음
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
> [16주차] JAVA: 멀리 뛰기

- programmers/algorithm/level2/sung-silver/예상_대진표.java
- 예상 대진표: https://school.programmers.co.kr/learn/courses/30/lessons/12985
- 내 현재 번호 +1 / 2를 하면 그 라운드에서 이겼을 때 부여받는 번호가 된다
- 구현? 뭐지 이런건
- 내 현재 번호 +1 / 2를 하면 그 라운드에서 이겼을 때 부여받는 번호가 되며 A, B의 번호가 1차이가 되면 대진이 끝난다고 생각했으나..! 아니었다 ㅋ
- 결론은 A와 B가 +1 /2 한 값이 같아지면 같은 라운드에서 경기를 한 것이다!
- 시간복잡도 : O(logn)
- 공간복잡도 : O(n)
- 반례를 찾는데 조금 어려웠는데 너무 단순했다
- 처음 코드에서 절댓값의 차이가 1이면 answer++를 하고 답을 반환했는데 생각해보니 4,5라고해서 같은 라운드에 경기하는 것은 아니었음..
> [16주차] JAVA: 예상 대진표

- programmers/algorithm/level2/hellozo0/week17/영어_끝말잇기.java
https://school.programmers.co.kr/learn/courses/30/lessons/12981?language=java
조건을 나눠서 3가지로 추렸다. 그리고 조건이 다 아닐 경우에는 없는 걸로 if문 하나더
결국은 4개의 조건이다
???..음....? 구현?
조건에 맞게 if문으로 식을 세워서...
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
그냥 노가다로 if 문으로 풀었는데 뭐나 효율적이다거나 그런 것은 아니다
``
if(set.contains(words[i]) || prev.charAt(prev.length() - 1) != words[i].charAt(0)){
```
요런식으로 ||로 연결하면 if문을 줄일수도 있는듯하다
효율적?이게 다른 사람 코드도 그닥...그냥 ||로 푼거 같은데 어케푸노!!!!!!!!!!
> [17주차] JAVA : 영어 끝말잇기

- programmers/algorithm/level2/hellozo0/week17/귤_고르기.java
https://school.programmers.co.kr/learn/courses/30/lessons/138476
노가다로 ....ㅜ
구현,..?
일단은 귤의 크기 배열을 정렬 후에 같은 크기가 몇개씩 나왔는지 구한다
1은 1개, 2는 2개, 3은 2개 등등..
그 후에 1,2,2, -> 그룹의 크기를 새로운 배열에 담고 원래 주어진 k 값에 새 배열의 가장 큰 값들을 우선으로 빼준다..! 
- 시간복잡도 : O(nlogn) -> Arrays.sort를 사용했기에...
- 공간복잡도 : O(n)
이 또한... 노가다성 구현....
> [17주차] JAVA : 귤 고르기

- programmers/sql/sung-silver/없어진_기록_찾기.sql
- 없어진 기록 찾기: https://school.programmers.co.kr/learn/courses/30/lessons/59042#
- right join 문제군
- right join(left join도 가능) 테이블 순서의 중요성
- IS NULL
- right join으로 outs 테이블에는 존재하지만 ins 테이블에는 존재하지 않는 정보를 출력
> [17주차] SQL: 없어진 기록 찾기

- programmers/algorithm/level2/sung-silver/영어_끝말잇기.java
- 영어 끝말잇기: https://school.programmers.co.kr/learn/courses/30/lessons/12981
- 문자열 앞뒤 비교 및 이미 중복된 단어 검사
- Set, 문자열
- 일단 나온 단어를 Set에 저장해서 중복 여부를 검사하고, 이전 문자의 끝 글자와 현재 문자의 앞글자를 비교한다
- 그 사람의 번호는 나머지로 구할 수 있고, 해당 단어를 말한 순서(턴)은 나누기로 구할 수 있다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
> [17주차] JAVA: 영어 끝말잇기

- programmers/algorithm/level2/sung-silver/귤_고르기.java
- 귤 고르기: https://school.programmers.co.kr/learn/courses/30/lessons/138476
- 귤 사이즈를 Key, 총 개수를 value로하는 해시맵 만들기
- HashMap, 정렬?
- 귤 사이즈를 Key, 총 개수를 value로하는 해시맵 만들기
- value를 기준으로 내림차순 정렬 후 각 value 값의 합(count)이 k보다 같거나 커지는 시점의 구하기(answer를 증가)
- 공간복잡도 : O(n)
- 처음에 귤의 종류가 최소가 아니라 귤의 사이즈가 최소가 되면서 k개를 만족해야한다고 이해하고 dp처럼 왼쪽이나 오른쪽을 더하는 코드를 고민해서 시간을 좀 낭비함.. 단순한 문제였던 것 같음 ㅎ..
> [17주차] JAVA: 귤 고르기

- programmers/algorithm/level2/sung-silver/연속_부분_수열_합의_개수.java
- 연속 부분 합의 개수: https://school.programmers.co.kr/learn/courses/30/lessons/131701
- 합이 중복되지 않아야 함 -> set
- set
- 원형 수열이므로 인덱스가 넘어갈 경우 다시 앞으로 가야함 -> 나머지를 이용하여 인덱스 조절
- 혼자부터 모든 원소를 다 더할 수 있으므로 이 경우를 set에 모두 저장하면서 중복을 제거
- 공간복잡도 : O(N)
> [17주차] JAVA: 연속 부분 합의 개수

- programmers/algorithm/level2/Hong0329/영어 끝말잇기.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/12981
* map을 사용해야겠다.
* map
* map 을 통해서 해당 단어가 나왔음을 체크한다.
* if문으로 앞의 단어의 끝과 현재 단어의 처음이 같은지 비교한다.
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
X
> [17주차] C++ : 영어 끝말잇기

- programmers/algorithm/level2/Hong0329/귤 고르기.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/138476
* map을 통해서 귤의 크기별 개수를 구한다.
* 개수가 큰 걸 기준으로 정렬 후에 조건에 만족할 때까지 더해본다.
* map
* map을 통해서 귤의 크기별 개수를 구한다.
* 개수가 큰 걸 기준으로 정렬 후에 조건에 만족할 때까지 더해본다.
- 공간복잡도 : O(n)
X
> [17주차] C++ : 귤 고르기

- programmers/algorithm/level2/Hong0329/연속 부분 합의 개수.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/131701
* set
* set
* 2중 for문을 통해서 부분 합의 길이와 시작점을 잡고 합을 set에 저장.
* 넘거가는 것은 나누기로 처리
- 공간복잡도 : O(n)
X
> [17주차] C++ : 연속 부분 합의 개수

- programmers/algorithm/level2/hellozo0/week17/연속_부분_수열_합의_개수.java
https://school.programmers.co.kr/learn/courses/30/lessons/131701?language=java
음 .... 인덱스 조합해서../?
구현? 
0 번째 부터 뒤로 0~5개 -> 근데 length로 나눈 나머지....인덱스로 접근 
- 시간복잡도 : O(n^2)..? ^3..? 
첨에 아이디어 접근 법이 와젼 달랐다.. ㅠㅠ 그냥 기준 하나 잡고 
0 번째
0 번째 부터 뒤로 0~5개 -> 근데 length로 나눈 나머지....인덱스로 접근 --> 순환되게 이 아이디어가 안 떠올랐다 
이런 거는 주로 반복문이 많고 연관되어 있는데 ㅠ 이런 부분 약함 나중에 다시 풀업봐야지ㅏ...
--> 너무 어려우면 그냥 반복문 개수를 줄이고 sublist 인덱스로 접근해서 구하기
> [17주차] JAVA : 연속 부분 수열 합의 개수

- programmers/sql/Hong0329/부서별 평균 연봉 조회하기.sql
* 부서별 평균 연봉 조회하기
* 그룹바이, 조인
* 그룹바이, 조인
없습니다.
> [18주차] SQL : 부서별 평균 연봉 조회하기

- programmers/algorithm/level2/Hong0329/할인 행사.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/131127
* map사용
* 자료구조(맵)
* 맵에 상품과 개수를 다 저장한다.
* 입력받은 할인 정보들에 대해서 해당 맵에 있는 값들을 다 만족하는지 10단위로 탐색한다.
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
X
> [18주차] C++: 할인 행사

- programmers/algorithm/level2/Hong0329/n^2배열 자르기.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/87390
* 규칙 찾기?구현?
* 규칙 찾기?구현?
* i행 j열의 값은 i j 중 더 큰 값에 +1을 한 값이다.
* 행렬에서 index번째의 행과 열을 구할 때 행은 index/N, 열은 index%N으로 구한다.
- 공간복잡도 : O(N)
* 규칙이 안보여서 구글링했다.....똑똑한 사람들....
> [18주차] C++ : n^2 배열 자르기

- programmers/algorithm/level2/hellozo0/week18/할인행사.java
https://school.programmers.co.kr/learn/courses/30/lessons/131127?language=java
음 일단 바로 앞뒤 간격 조정 -> 이진탐색?인가 생각함
이진탐색?
음 일단은 이진탐색으로, start & end 를 조정하면서 조건에 맞는지 체크하는 방식으로 진행..!
- 시간복잡도 : O(n^2) -> valid 함수에도 반복문 있슴 ㅠ
- 공간복잡도 : O(n)
if문 파티다...
> [18주차] JAVA : 할인 행사

- programmers/algorithm/level2/hellozo0/week18/n2배열자르기.java
https://school.programmers.co.kr/learn/courses/30/lessons/87390?language=java
음 DP인가>.?
그리디인가? 뭐지?
index에 값이 어떻게 할당 되는지 잘 생각해서.... 규칙 찾기!~
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
아 원래 배열에 값 다 할당하고 -> 그 후 원하는 index만 추출할라고 했는데 13번테스트케이스 부터 뒤에까지 다 런타임에러랑 & 메모리 초과가 났따...
그래서 다시 조건 생각해보니 처음부터 answer에 값을 할당하는게 효율적인것을 알게 되었음! 
근데?!!!! 또 틀려서 보니까 int long 을 적절히 변환해가면서 해야햇음 ㅠㅠ 결론은 해결~
> [18주차] JAVA : n^2 배열 자르기

- programmers/algorithm/level2/hellozo0/week18/괄호_회전하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/76502?language=java
이전 문제와 비슷한 유형이라 기억함 - 스택 문제
스택
이전 괄호 문제랑 똑같다 여는 괄호 일떄는 스택에 넣어주고, 닫는 괄호일때는 바로 앞에 꺼가 짝이 맞는지 확인하고 pop한다
💡 map으로 짝 검색 vs if 노가다로 풀기 뭐가 더 빠른가 봤는데, map은 메모리를 더 쓰고, 근데 시간이 더 짧은게 있고 더 조금씩 더 긴게 있고 둘다 비슷비슷해서 ...음......뭘 쓰든 의미 없는것 같다>
- 공간복잡도 : O(N)
if-else를 최대한 덜 쓰고 싶었는데........
> [18주차] JAVA : 괄호 회전하기

- programmers/sql/sung-silver/조건에_맞는_사용자_정보_조회하기.sql
- 조건에 맞는 사용자 정보 조회하기: https://school.programmers.co.kr/learn/courses/30/lessons/164670
- group by, having
- 문자열(concat, substr)
- group by, having
- having으로 집계함수(count)의 값이 3 이상인 회원의 정보 출력
- 정규표현식으로 전화번호를 바꾸려고했지만 수식이 기억나지 않았..다
- ㅋㅋ ㅜ.ㅜ
> [18주차] SQL: 조건에 맞는 사용자 정보 조회하기

- programmers/sql/sung-silver/부서별_평균_연봉_조회하기.sql
- 부서별 평균 연봉 조회하기: https://school.programmers.co.kr/learn/courses/30/lessons/284529
- 놀랍게도 우리학교 시험문제랑 똑같다!
- group by, join
- 부서별로 묶고 요구하는 정보 출력
> [18주차] SQL: 부서별 평균 연봉 조회하기

- programmers/algorithm/level2/sung-silver/괄호_회전하기.java
- 괄호 회전하기: https://school.programmers.co.kr/learn/courses/30/lessons/76502?language=java
- 괄호 짝짓기다!
- 스택
- 스택에 넣어서 짝에 맞는 괄호인지 확인
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- sql 풀다 풀어서 substring을 substr이라고 씀 ㅋ..
> [18주차] JAVA: 괄호 회전하기

- programmers/algorithm/level2/sung-silver/할인행사.java
- 할인 행사: https://school.programmers.co.kr/learn/courses/30/lessons/131127
- HashMap
- 단순 구현?
- 10일씩 행사되는 상품의 갯수를 Map에 저장하고 최종적으로 저장된 값과 구매하고자하는 수량을 비교
- 공간복잡도 : O(N)
- 문제를 제대로 안읽어서 구매할 수 있는 최초의 일자를 구해서 틀렸음..ㅎ
> [18주차] JAVA: 할인 행사

- programmers/algorithm/level2/sung-silver/n^2_배열_자르기.java
- n^2 배열 자르기: https://school.programmers.co.kr/learn/courses/30/lessons/87390
- 규칙을 찾아야한다..
- dp?
- Math.max(행, 열)이 그 행열의 값임
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 시간초과 이슈..
- 시간 초과가 나면 일단 규칙을 찾으려고 노력하기
> [18주차] JAVA: n^2 배열 자르기

- programmers/sql/hellozo0/date/자동차 대여 기록 중에서 대여중 대여가능 여부 구분하기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/157340
아 그 날짜르 ㄹ어떻게 해야할지 감을 못잡음 ㅠ 구글링 했삼요
그룹바이 유형이라는데 솔직히 date 유형이 가까움 - 어떻게 조건 세울 건지가 중요한듯함
자동차 아이디로 그룹 묶고, 그 날짜 조건에 맞는 case-when-then-else-end 절 세우고, 가장 값이 큰거 --> 가장 최근꺼임! 
요 조건으로 도출!
날짜 어떻게 해야하나 고민했음 , 그리고 최근 꺼를 history 아이디 가장 큰 값으로 하면 최신꺼라 하긴 했는데 나중에 되면 조건 더 까다로운 것도 나올듯
> [19주차] SQL : 자동차 대여 기록 중에서 대여중 / 대여가능 여부 구분하기

- programmers/sql/hellozo0/case/대장균의 크기에 따라 분류하기 1.sql
https://school.programmers.co.kr/learn/courses/30/lessons/299307
이번에도 case-when-then 절~ 이전꺼보다 쉬움 개꿀
case
case when <크기가 어디 범위에 해당하는지 > then 'LOW' -> 이런식으로 조건식 세우기
>  [19주차] SQL : 대장균의 크기에 따라 분류하기 1

- programmers/algorithm/level2/hellozo0/week19/행렬의곱셈.java
https://school.programmers.co.kr/learn/courses/30/lessons/12949
행렬 어떻게 구하는지 그 어디랑 어디랑 곱하는지 알아야한다!!!
음 행렬..? 수학.? 
그 곱하고 더하는 인덱스를 i,j,k로 해서 반복문으로 누적합! 
- 시간복잡도 : O(n^3) 
>  [19주차] JAVA : 행렬의 곱셈

- programmers/algorithm/level2/hellozo0/week19/의상.java
https://school.programmers.co.kr/learn/courses/30/lessons/42578
이전에 풀었음 ^_^...ㅎㅎ.. 그리고 항목 별로 넣는거는 containsKey함수 쓰면 편해서 해시 쓰는게 편함! 
해시가 그 값을 찾는 시간 복잡도는 얼만지 모르겠지만.. 
해시
1. 해시를 사용해서 Key에는 종류 항목 - Value에는 가지고 있는 가지수 누적합
2. 결과는 개수+1(선택안하는경우)가지수를 다 곱하고 -1(모두 선택 안하는 경우) 해준다.
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
>  [19주차] JAVA : 의상

- programmers/algorithm/level2/hellozo0/week19/H_Index.java
https://school.programmers.co.kr/learn/courses/30/lessons/42747
정렬 + 조건 생각
정렬
정렬 한 후에, 
개수와 해당 index 값의 비교를 통해 구한다..
- 시간복잡도 : O(nlogn) _> Sort
- 공간복잡도 : O(n)
저번에도 이거 못 문제 이해를 잘못해서 못풀었는데 이번에도....ㅠ
> //[19주차] JAVA : H-Index

- programmers/algorithm/level2/sung-silver/행렬의_곱셈.java
- 행렬의 곱셈: https://school.programmers.co.kr/learn/courses/30/lessons/12949
- 흠..dp?
- dp인가..? 단순 구현인가..
- 행렬..식을 세우면 됨
- 시간복잡도 : O(N^3)
- 공간복잡도 : O(N)
- 순간 행렬 까먹음 ㅎ
> [19주차] JAVA: 행렬의 곱셈

- programmers/sql/Hong0329/자동차 대여 기록에서 대여중대여 가능 여부 구분하기.sql
* 자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기
* case문을 통해서 조건을 따져본다.
* case, group by
* case문을 통해서 조건을 따져본다.
* case문 어렵네요... 구글링 했습니다ㅜㅜ
> [19주차] SQL : 자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기

- programmers/algorithm/level2/sung-silver/의상.java
- 의상: https://school.programmers.co.kr/learn/courses/30/lessons/42578
- 조합..문제
- 조합, 수학? 구현?
- 조합 착착...(개수+1)끼리 곱하고 맨마지막에 1을 감소
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
> [19주차] JAVA: 의상

- programmers/sql/Hong0329/대장균의 크기에 따라 분류하기 1.sql
* 대장균의 크기에 따라 분류하기 1
* case문 사용하기.
* case
* case문을 사용하여, size_of_colony의 값에 대해 주어진 조건과 비교해본다.
* 자동차 대여 문제를 먼저 해결했었어서 비교적 할만 했다.
> [19주차] SQL : 대장균의 크기에 따라 분류하기 1

- .idea/workspace.xml
- programmers/algorithm/level2/Hong0329/행렬의 곱셈.cpp
* 행렬의 곱셈
* 3중 for문을 통해서 각각의 곱을 다 구하고, 맞춰서 answer벡터에 집어넣는다.
* 구현
* 3중 for문을 통해서 각각의 곱을 다 구하고, 맞춰서 answer벡터에 집어넣는다.
- 시간복잡도 : O(n^3)
- 공간복잡도 : O(n)
X
> [19주차] C++ : 행렬의 곱셈

- programmers/algorithm/level2/Hong0329/H-Index.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42747
* 문제에서 제시하는 조건에 맞는 규칙을 찾아야 한다.
* 정렬
* 주어진 논문 인용된 횟수들을 역으로 정렬한 후로 for문을 돌면서 i랑 citations[i]값을 비교한다. i -> 현재 논문보다 많이 인용된 논문의 개수를 의미하기 때문
- 시간복잡도 :O(n)
- 공간복잡도 :O(n)
> [19주차] C++ : H-Index

- programmers/algorithm/level2/sung-silver/H-index.java
- H-Index
- 어떤 논문의 인용 횟수와 그 인용횟수 이상인 논문의 개수 비교하기
- 정렬
- 어떤 논문의 인용 횟수와 그 인용횟수 이상인 논문의 개수 비교하기
- 시간복잡도 : O(NlogN)
- 공간복잡도 : O(N)
- 예전 풀이도 봤는데 정렬해두고 이중포문을 써서 비교하던데.. 왜그랬을까 이렇게 간결한데
> [19주차] JAVA: H-Index

- programmers/algorithm/level2/hellozo0/week20/캐시_정답버전.java
- programmers/algorithm/level2/hellozo0/week20/캐시_틀린버전.java
https://school.programmers.co.kr/learn/courses/30/lessons/17680
일단 조건을 잘 생각해서 어떤 기준으로 +=5 +=0 하는지 생각
조건에 따라 arraylisty에 넣고 빼고 하기
아 리스트가 삭제 하면 알아서 순서 앞으로 땡겨지는 원리?를 미처 생각치 못해서 큐로 노가다 방법만 떠오름..
제일 흔한 자료구조의 기능을 잘 알아둬야할듯!
여윽시 카카오다.... hashmap이나 큐 스택같이 흔한거 아니고 기본으로..조지깅..
>  [20주차] JAVA : 캐시

- programmers/algorithm/level2/hellozo0/week20/이중우선순위큐.java
https://school.programmers.co.kr/learn/courses/30/lessons/42628
이중우선순위 큐의 기능을 알아야한다
이중우선순위큐
2개의 이중우선순위를 사용하고 remove(삭제할값)을 잘 써야함!
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)..?
ㄴㄴ
> [20주차] JAVA : 이중우선순위큐

- programmers/algorithm/level2/hellozo0/week20/기능개발.java
https://school.programmers.co.kr/learn/courses/30/lessons/42586
음... 스택 큐라고 적혀있지만 일단 그냥 풀어보고 편한방법 택함
스택 큐 또는 배열
1. 일단 몇일 걸리는지 계산
2. 조건에 맞게 크기 비교 한후 정답 배열에 값저장
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
>  [20주차] JAVA : 기능개발

- programmers/sql/hellozo0/subQuery/조회수가_가장많은_중고거래_게시판의_첨부파일_조회하기.sql
일단 처음에는 조인으로 풀까 생각했는데,,,, 하다가 계속 틀려서 서브쿼리로 바꿈
서브 쿼리
concat
concat은 뭐 쉽고, 서브쿼리가 LIMIT을 쓸거면 IN을 쓰면 안된다 =로 써야함!!! 귀한거 알았다
> [21주차] SQL : 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기

- programmers/algorithm/level2/hellozo0/week21/정수삼각형.java
https://school.programmers.co.kr/learn/courses/30/lessons/43105?language=java
dp인데 어떻게 누저합 max 를 구할건지?! 에 대한것을 식을 세우면된다...
dp!!
dp인데! 어떻게 max 값을 구할건지 인덱스 비교 할 대상 계산..해서...
- 공간복잡도 : o(n^2)
> [21주차] JAVA : 정수 삼각형

- programmers/algorithm/level2/Hong0329/튜플.cpp
* 튜플
* 집합의 길이에 해당하는 v[length]번째에 쪼개진 집합의 원소들을 넣는다.
* 집합의 길이1부터 최대 길이까지 확인한 적 없는 원소를 answer에 넣는다.
* 구현
* 집합의 길이에 해당하는 v[length]번째에 쪼개진 집합의 원소들을 넣는다.
* 집합의 길이1부터 최대 길이까지 확인한 적 없는 원소를 answer에 넣는다.
- 공간복잡도 : O(n)
> [21주차] C++ : 튜플

- programmers/algorithm/level2/Hong0329/정수 삼각형.cpp
* 정수 삼각형
* dp
* DP 
* 삼각형을 거꾸로 뒤집어서 그림의 아래에서부터 위 꼭짓점까지 더해가는 식으로 점화식을 작성한다.
- 시간복잡도 : o(n^2)
- 공간복잡도 : o(1) 입력을 포함하면 o(n^2)
> [21주차] C++ : 정수 삼각형

- programmers/algorithm/level2/Hong0329/피로도.cpp
* 피로도
* 완전탐색
* 완전탐색
* 모든 순열에 대해서 할 수 있는 일의 개수를 따져본다.
- 시간복잡도 : O(n!*n) -> gpt가 그렇대요....ㅎ
- 공간복잡도 : O(n)
> [21주차] C++ : 피로도

- programmers/algorithm/level2/sung-silver/1차_캐시.java
- 1차 캐시: https://school.programmers.co.kr/learn/courses/30/lessons/17680
- 캐시로직을 어떤 자료구조로 구현해야 할 것인가?
- 운영체제 지식이 필요했다..
- LRU를 생각하여 add, remove를 진행
- 공간복잡도 : O(N)
- 늦어서 죄송합니더.. 근데 서로 리뷰하셨길래 저는 두분 다 태그할게요 .ㅋ.ㅋ.
> [20주차] JAVA: [1차] 캐시

- programmers/sql/sung-silver/취소하지_않은_예약_조회하기.sql
- 취소되지 않은 진로 예약 조회하기
- 두번 조인해야할 것 같음
- 이중 조인
- 조인을 두번해서 풀이
- 무난했다!
> [20주차] SQL: 취소되지 않은 진로 예약 조회하기

- programmers/algorithm/level2/sung-silver/이중우선순위큐.java
- 이중우선순위큐
- 힙을 사용하자!
- 힙
- 최대값은 최대힙에서, 최소값은 최소힙으로 찾는다!
- 이전에 풀었던 유형이라.. 힙을 떠올릴 수 있었다
- 공간복잡도 : O(N)
> [20주차] JAVA: 이중우선순위큐

- programmers/algorithm/level2/sung-silver/기능개발.java
- 기능개발
- 남아있는 작업을 하루 작업량으로 나누고 그 몫을 큐에 담아 비교하기
- 큐
- 큐에 담긴 몫을 비교한다 -> 앞에 꺼낸 것 보다 몫이 작으면 앞에 기능이 배포될 때 함께 배포된다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
> [20주차] JAVA: 기능개발

- programmers/algorithm/level2/sung-silver/튜플.java
- 튜플
- 예전에 푼 문제인데 정렬 기준이 생각나지 않음..
- 해시맵이라고 생각
- 입력 값의 원소의 개수를 카운트하여 정렬하고 그대로 반환
- 공간복잡도 : O(n)
- 예전에도 그랬는데 숫자의 개수대로 정렬하는거를 입출력 값보고 예측하는건지.. 아님 내가 놓치고 있는게 있는건지 의문
> [21주차] JAVA: 튜플

- programmers/algorithm/level3/sung-silver/정수_삼각형.java
> [CHORE] level3 문제 위치 변경

- .idea/workspace.xml
- programmers/algorithm/level3/Hong0329/네트워크.cpp
* 네트워크
* dfs
* dfs
* dfs
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
> [22주차] C++ : 네트워크

- .idea/workspace.xml
- programmers/algorithm/level2/Hong0329/프로세스.cpp
* 프로세스
* 문제 조건에 맞는 순서를 만들어놓고 입력받은 값이랑 비교
* 자료구조, 구현
* 문제 조건에 맞는 순서를 만들어놓고 입력받은 값이랑 비교
- 시간복잡도 : o(nlogn)
- 공간복잡도 : o(n)
> [22주차] C++ : 프로세스

- programmers/sql/Hong0329/우유와 요거트가 담긴 장바구니.sql
* 우유와 요거트가 담긴 장바구니
* 두 개의 조건을 어떻게 합쳐서 보는지가 관건이었던거같습니다.
* with문 사용
* 구글링했어요..
> [22주차] SQL: 우유와 요거트가 담긴 장바구니

- programmers/algorithm/level2/hellozo0/week22/프로세스.java
https://school.programmers.co.kr/learn/courses/30/lessons/42587
음..일단 프로세스 의 들어가고 나가는 순서가 내림차순으로 되어있기에 우선순위 큐를 사용해야겠다고 판단했음
우선순위큐
우선순위 큐에 값을다 넣은 다음
1. 먼저 뽑은 값이 주어진 배열의 어느인덱스인지 파악한다
2. 그 후로 뒤로는 그 다음 큰값에 대해서 바로 뒤 인덱스부터 비교를 또 하기 때문에 같은 동점이더라도 조건에 맞는 인덱스 순으로... 찾아진다!
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
>  [22주차] JAVA : 프로세스

- programmers/algorithm/level2/sung-silver/프로세스.java
- 프로세스
- 프로세스에 대한 위치정보와 우선순위 정보를 하나의 클래스로 만들어 정렬하자
- 큐
- 큐를 만들어 우선순위 리스트(정렬된)와 비교한다
- 공간복잡도 : O(n)
- 이전에 풀었던 방법이 생각나서 그렇게 풀었는데 현주언니처럼 우선순위큐나 다른 자료구조도 고려해볼 것!
> [22주차] JAVA: 프로세스

- programmers/sql/sung-silver/저자_별_카테고리_별_매출액_집계하기.sql
- 저자 별 카테고리 별 매출액 집계하기
- group by, 집계함수
- group by
- SUM에 들어가지 않는 필드는 모두 group by에 명시
- X
> [22주차] SQL: 저자 별 카테고리 별 매출액 집계하기

- programmers/algorithm/level2/sung-silver/1차_뉴스_클러스터링.java]
- [1차] 뉴스 클러스터링
- 해시맵을 사용해야겠다!
- 교집합과 합집합을 생각하는 문제
- 교집합을 구할 때에는 str1에 대한 해시맵과 str2에 대한 해시맵에서 더 작은 값을 더한다
- 반대로 합집합일 때에는 더 큰 값을 더한다
- 중복을 피하기 위해 str1과 비교했던 값들은 0으로 변경하여 마지막에 str2에 대해서 검사한 후 합집합 계산을 끝낸다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
- 부동 소수점 계산..을 어떻게 해야할지 몰랐는데 (int)만 붙여주면 되는거였다
> [22주차] JAVA: [1차] 뉴스 클러스터링

- programmers/algorithm/level3/sung-silver/네트워크.java
- 네트워크
- dfs
- dfs
- 이 컴퓨터랑 연결된 컴퓨터가 있는가? -> visited로 검사
- 방문되지 않았다면 거기서부터 새로운 네트워크 형성 가능
- 공간복잡도 : O(N)
- 처음에 감이안와서.. 예전 풀이를 좀 봤다! 근데 그 당시에는 visited를 set으로 두고 풀었던데 그거보다 지금 짠 코드가 더 직관적으로 이해할 수 있는 것 같다 ^_^
> [22주차] JAVA: 네트워크

- programmers/algorithm/level2/hellozo0/week23/전화번호목록.java
https://school.programmers.co.kr/learn/courses/30/lessons/42577
소올직히 해시인거 모르고 풀면 그냥 문자열로 풀고 효율성 검사 탈락해서 망할거 같음 ....ㅠㅠㅠ
그나마 substring으로 풀 생각했는데 그렇게 하면... 아마 그 되긴 될라나..? 일단 반복문을 2개 쓰면 안된다 
해시라고 하는데 문자열도 가능
배열을 길이 별로 정렬 한후에,
문자열 길이 < 다음 문자열 길이 라는 조건하에 StartWith 써서 시작하는지 판단한다 
endWith도 있는듯 하다
- 시간복잡도 : O(nlogn) --> 정렬
- 공간복잡도 : O(n)
아 자꾸 효율성 검사에서 안되서 구글링 해봄 ㅠㅠ  정렬 하면 그냥 i < i+1 이렇게만 검사 해봐도 되는듯 하다 
악 대박 주어진 입력값이 String으로 주어져서 Sort 하면 123, 12345, 567 이런식으로 문자기준 오름차순이 된다... 그래서 앞뒤 글자로 비교 해도 되는거싱였다....와웅.. 그냥 해시 떠오르는게 쉬울듯
뭔가를 찾는다 --> 해시(빠르니까) 이걸 떠올리자..!!!!!
> [23주차] JAVA : 전화번호 목록

- programmers/algorithm/level2/hellozo0/week23/타겟넘버.java
https://school.programmers.co.kr/learn/courses/30/lessons/43165
음 dfs로 모든 경우 다 탐색할 필요가 있어야했다. +1 -1 인지 모든 케이스 다 탐색
dfs
dfs! 로 모든 경우 다 꼬리물기로 탐색
- 시간복잡도 : O(N+E) 
- 공간복잡도 : O(N)
> [23주차] JAVA : 타겟 넘버

- programmers/algorithm/level3/hellozo0/week23/야근지수.java
https://school.programmers.co.kr/learn/courses/30/lessons/12927?language=java
음 딱 보자마자 큰 놈들만 -1 씩 해줌되게따! -> 우선순위 큐 쓰자! 
쉬웠따 이런것만 코테 나오면 10분 컷인데
유형,,,>? 큐..?
우선순위 큐에 값을 다 넣고, poll 한 값들에 -1씩 해주고 다시 넣는다 (이 과정을 n 번 한다) 
그리고 pow로 제곱근 누적합~
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
없음
> [23주차] JAVA : 야근 지수

- programmers/sql/sung-silver/헤비_유저가_소유한_장소.sql
- 헤비 유저가 소유한 장소
- group by
- group by, having
- having count가 2 이상인 애들을 출력
> [23주차] SQL: 헤비 유저가 소유한 장소

- programmers/algorithm/level2/전화번호_목록.java
- 전화번호 목록
- 해시
- 해시
- 전화번호를 key로 저장하고, 다시 돌면서 비교했을 때 포함되면 true
- 공간복잡도 : O(N)
> [23주차] JAVA: 전화번호 목록

- programmers/algorithm/level2/타겟_넘버.java
- 타겟 넘버
- dfs
- dfs
- 경우의 수를 다 만들어보고 그 숫자가 되면 된다
- 시간복잡도 : O(2^N)
- 공간복잡도 : O(N)
> [23주차] JAVA: 타겟 넘버

- programmers/algorithm/level3/야근_지수.java
- 야근 지수
- 이런건 뭐라해야할까 단순 구현?
- 이런건 뭐라해야할까 단순 구현? 우선순위큐,..?
- 큰 친구들부터 -1하면서 다시 큐에 넣고 제곱근 레츠고
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
> [23주차] JAVA: 야근 지수

- programmers/algorithm/level2/Hong0329/전화번호 목록.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/42577
* String을 Sort한 후에, for문을 돌면서 현재 값과 다음 값만 서로 비교한다.
* 이때 뒤의 값은 앞의 값의 길이 만큼만 잘라서 비교하며, 그것이 같다면 false반환
* 자료구조
* String을 Sort한 후에, for문을 돌면서 현재 값과 다음 값만 서로 비교한다.
* 이때 뒤의 값은 앞의 값의 길이 만큼만 잘라서 비교하며, 그것이 같다면 false반환
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
X
> [23주차] C++ : 전화번호 목록

- programmers/algorithm/level2/Hong0329/타겟 넘버.cpp
* https://school.programmers.co.kr/learn/courses/30/lessons/43165
* 구간 별로 더하는 것, 빼는 것 트리 형식으로 볼 수 있겠다.
* DFS
* dfs재귀를 통해서 처음 인덱스부터 맨끝 인덱스까지 돈다.
* 이때 구간 별로 해당 값을 더하거나 빼는 가지를 만들어서 진행한다.
- 시간복잡도 : O(2^n)
- 공간복잡도 : O(n)
* 없습니다.
> [23주차] C++ : 타겟 넘버

- programmers/algorithm/level3/Hong0329/야근 지수.cpp
* 야근 지수
* 우선순위큐
* 우선순위큐, 수학
* 우선순위 큐로 정렬한 후 가장 큰 애들을 1씩 줄인다. 작업 시간 만큼
* 큰 숫자가 있을 수록 제곱한 값이 엄청 커진다는 점을 이용
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
X
> [23주차] C++ : 야근 지수

- programmers/algorithm/level2/sung-silver/k진수에서_소수_개수_구하기.java
- K진수에서 소수 개수 구하기
- 구현
- 수학?
- isPrime 함수 만들어서 소수인지 판단
- 공간복잡도 : O(N)
> [24주차] JAVA: K진수에서 소수 개수 구하기

- programmers/algorithm/level2/Hong0329/[3차] n진수 게임.cpp
* [3차] n진수 게임
* 16진수까지의 배열을 임의로 만들어 놓고 사용
* 문자열 
* 16진수까지의 배열을 임의로 만들어 놓고 사용
시간복잡도 : O(n)
공간복잡도 : O(n)
X
> [24주차] C++ : [3차] n진수 게임

- .idea/workspace.xml
- programmers/algorithm/level2/Hong0329/k진수에서 소수 개수 구하기.cpp
* k진수에서 소수 개수 구하기
* k진수 숫자로 변환한 후에 0을 기준으로 파싱 및 판별
* 구현?
* k진수 숫자로 변환한 후에 0을 기준으로 파싱 및 판별
시간복잡도 : O(n)
공간복잡도 : O(n)
X
> [24주차] C++ : k진수에서 소수 개수 구하기

- programmers/algorithm/level3/Hong0329/단어 변환.cpp
* 단어 변환
* dfs를 사용하여 바뀔 수 있는 단어들을 다 가본다.
* 주어진 words에 target이 없다면 dfs를 돌리기 전에 0을 출력한다.
* dfs
* 시작 단어로 부터 바뀔 수 있는 단어로 바뀌어 본다.
* 바뀐 후에 또 바뀔 수 있는 단어들을 찾아보며 바뀌어본다. 
* 원하는 단어가 된다면 그때의 횟수를 answer에 저장해놓는다.
- 공간복잡도 : O(n)
* 없습니다.
> [24주차] C++ : 단어 변환

- programmers/algorithm/level3/hellozo0/week24/단어변환.java
https://school.programmers.co.kr/learn/courses/30/lessons/43163
dfs -> 재귀의 느낌이 났기 때문에.!
dfs
dfs로 조건에 맞게 그 차이나는 글자소가 1개일 경우 dfs를 다시 하는~...그런 엔딩
- 시간복잡도 :  O(N^2)
- 공간복잡도 : O(N)
> [24주차] JAVA : 단어 변환

- programmers/algorithm/level2/hellozo0/week24/k진수에서_소수_개수_구하기.java
https://school.programmers.co.kr/learn/courses/30/lessons/92335
음 아까랑 같이 진수 문제.>!
문자열
이또한 원하는 진수로 변환한 후에 0을 기준으로 split하고 소수 여부 파악..! 
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
자꾸 런타임 에러가 났는데 ..long 이여야해서 그런거 여따...뚀륵
> [24주차] JAVA : k진수에서 소수 개수 구하기

- programmers/algorithm/level2/hellozo0/week24/n진수_게임.java
https://school.programmers.co.kr/learn/courses/30/lessons/17687?language=java
문자열..인데....내장함수를 잘 기억하고 있어야...
문자열...
주어진 길이만큼 주어진 진수로 바꾸고 ~... 저장해두고 p의 차례에 맞게 t개 만큼 추려서 출력
처음에는 그 진수로 바꾸는 부분을 저장하는것을 String -> 배열로 저장하고 -> 반복문으로 배열의 해당 인덱스를 뽑아냈는데
구글링해보니 이분은 그냥 String으로 두셨길래 더 좋은거 가 ㅌ아서 가져왔다
- 시간복잡도 : O(n)
- 공간복잡도 : O(n)
머리로는 어떻게 풀어야하는지가 딱 알고 있는데 내장 함수 모르니까 죽고싶은 마음뿐...
아악! 그래서 구글링 했다
근데 처음에 짰던 코드랑 같은데 toUpper를 생각 못했다
카카오는 진짜 잘 안쓰는 내장함수 ? 쓰기의 달인이다
> [24주차] JAVA : [3차] n진수 게임

- programmers/algorithm/level2/hellozo0/week25/압축.java
일단 문자열 문제? 그리고 map을 쓴다?
문자열, Map
먼저 문자열 길이 만큼 첫번쨰 비교할 값, 두번째 비교할 값을 나누고
map에는 A~Z를 제외한 값만 넣을 거임,
그래서 사전(A~Z, map)에 있으면 first = temp로 하고,, 문자열 누적하고
아니면 first 출력 + 사전에 넣고, 등등 작업을 한다
- 시간복잡도 : O(N)
- 공간복잡도 : O(N)
귀차나서 함수 안 묶음 --> 그 반복 하는 if-else가 싫어서 반복문 안에서 어떻게 처리 해볼까 했는데 if문 계속 생기는게 싫어서 그냥~ 밖에다가 씀
>  [25주차] JAVA : [3차] 압축

- programmers/algorithm/level3/hellozo0/week25/등굣길.java
https://school.programmers.co.kr/learn/courses/30/lessons/42898
처음에 DFS로 풀었다
문제도 최단거리를 생각했다... 개수를 구해야하는데...~....ㅠㅡㅠ
DP
먼저 최단거리를 누적합해야한다. 그럴라면 위에서 오는거 왼쪽 에서 오는거의 개수를 더하면, 해당 위치까지 오는 최단거리의 개수를 구할 수 있다
- 시간복잡도 : O(N^2) --> 중첩 반복문
DFS로 풀라고 했더것... 좌표만 나오면 dfs,bfs를 생각한다... 좀더 넉넉하게 시간 잡고 문제 읽을것~!
> [25주차] JAVA : 등굣길

- programmers/algorithm/level2/hellozo0/week25/게임_맵_최단거리.java
[
](https://school.programmers.co.kr/learn/courses/30/lessons/1844)
최단거리 탐색? --> BFS
BFS
일단 좌우상하 좌표를 만들어서
현재 좌표 + 좌우상하 를 비교해서 방문안했으면 큐에 넣고 ~... 이런식으로 BFS 탐색
maps는 입력받는데 static으로 변수 선언 했다가 자꾸 nullpointer 에러가 나서 조건문이 잘못되었나??하고 오만거 다 테스트해보다가 챗지피티 선생님한테 물어봤다~ 
```
NullPointerException이 발생하는 이유는 BFS() 메서드 내에서 maps 변수를 참조하려고 하지만, 해당 변수가 초기화되지 않았기 때문입니다. maps는 인스턴스 변수로 선언되어 있지 않기 때문에 BFS() 메서드에서 바로 접근할 수 없습니다.
maps는 solution 메서드의 매개변수로 전달되었기 때문에, BFS() 메서드에서는 이 maps 변수를 참조할 수 없습니다. 이를 해결하기 위해 두 가지 방법이 있습니다:
1.	maps를 인스턴스 변수로 선언하여 클래스 내 모든 메서드에서 접근할 수 있도록 합니다.
2.	BFS() 메서드의 매개변수로 maps를 전달하여 사용합니다
```
> [25주차] JAVA : 게임 맵 최단거리

- programmers/sql/hellozo0/case/연간_평가점수에_해당하는_등급_및_성과금_조회하기.sql
https://school.programmers.co.kr/learn/courses/30/lessons/284528
일단 컬럼을 새로 만들어야한다..! 기준에 따라 --> 이럴 때 주로 CASE WHEN THEN ELSE END 절을 쓴다는것을 생각..!
GROUP BY CASE.?
먼저 조건에 맞게 데이터를 정리한 테이블이랑 조인을 한다음 -> CASE절로 조건에 맞게 데이터 나오게끔~...하기
근데 연산 진짜 많아질텐데 ..
> [25주차] SQL : 연간 평가점수에 해당하는 등급 및 성과금 조회하기
